---

# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: d3 Homepage

backgorund: https://i.imgur.com/L2qaxsm.jpeg 
theme: dark
iconStyle: theme
target: _self
headerStyle: boxedWidgets 
layout:
  
  Hypervisor:
    tab: Home
    style: row
    columns: 4 
    header: true
  Remote:  
    tab: Home
    style: row
    columns: 2
    header: false
  Mid:
    style: column
    column: 2
    header: true
    Infra:
    tab: Homelab
    Monitor:
      tab: Homelab
  Bot:
    style: column
    column: 4
    header: true
    Applications:
      tab: Homelab
  2nd Tab:
    tab: Cloud
    style: row
    columns: 4
  M365:
    tab: Cloud
    style: row
    columns: 4
  Other Cloud:
    tab: Cloud
    style: row
    columns: 4
  
  3rd Tab:
    tab: Corp
  Network:
    header: true
    tab: Corp
    style: row
    columns: 4  
  System:
    header: true
    tab: Corp
    style: row
    columns: 4 
  4th Tab: 
    tab: Monitoring
  GL1:
    tab: Monitoring
    style: row
    colums: 4
  GL2:
    tab: Monitoring
    style: row
    colums: 4
  GL3:
    tab: Monitoring
    style: row
    colums: 4
  


