---

# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: d3 Homepage

backgorund: https://i.imgur.com/L2qaxsm.jpeg 
theme: dark
iconStyle: theme
target: _self
headerStyle: boxedWidgets 
layout:
  
  Group1:
    tab: Home
    style: column
    columns: 1 
    header: true
    Root:
      style: row
      columns: 1
      header: false
    Top:
      style: row
      columns: 3 
      header: false
      useEqualHeights: true
    Mid:
      style: column
      rows: 2
      header: false
  Group2:
    tab: Home
    style: column
    columns: 1
    header: true
    useEqualHeights: true
    Infra:
      style: row
      columns: 4
      header: false
    Monitor:
      style: row
      columns: 4
      header: false
  Applications:
    tab: Home
    style: row
    columns: 4
    header: true
  M365:
    tab: Cloud
    style: row
    columns: 4
  Other Cloud:
    tab: Cloud
    style: row
    columns: 4
  
  Network:
    header: true
    tab: Corp
    style: row
    columns: 4  
  System:
    header: true
    tab: Corp
    style: row
    columns: 4 
  GL1:
    tab: Monitoring
    style: row
    colums: 4
  GL2:
    tab: Monitoring
    style: row
    colums: 4
  GL3:
    tab: Monitoring
    style: row
    colums: 4
  


