---

# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: d3 Homepage

backgorund: https://i.imgur.com/L2qaxsm.jpeg 
theme: dark
iconStyle: theme
target: _self
headerStyle: boxedWidgets 
layout:
  
  External:
    tab: Homelab
    style: column
    columns: 1
    header: false
    useEqualHeights: true
    Admin:
      style: row
      columns: 3
      header: true
      #useEqualHeights: true
    Monitoring:
      style: row
      columns: 4
      header: true
    Apps:
      style: row
      columns: 2
      header: true
  Internal:
    tab: Homelab
    style: column
    columns: 1 
    header: true
    Nas:
      style: row
      columns: 1 
      header: false
    Pve:
      style: row
      columns: 4 
      header: false
    M0nit0ring:
      style: row
      columns: 3 
      header: true
      useEqualHeights: true
    I1:
      style: row
      columns: 2
      header: false
    Local Apps:
      style: row
      columns: 4
      header: true
  M365:
    tab: Cloud
    style: row
    columns: 4
  Other Cloud:
    tab: Cloud
    style: row
    columns: 4
  
  Network:
    header: true
    tab: Corp
    style: row
    columns: 4  
  System:
    header: true
    tab: Corp
    style: row
    columns: 4 
  GL1:
    tab: Monitoring
    style: row
    colums: 4
  GL2:
    tab: Monitoring
    style: row
    colums: 4
  GL3:
    tab: Monitoring
    style: row
    colums: 4
  


