---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- datetime:
    format:
    timeStyle: short
    hour12: true
- logo:
    icon: /icons/d3logo.png 
- openmeteo:
    label: Singapore
    latitude: 1.27
    longitude: 103.8374
    timezone: Asia/Singapore
    cache: 5
    units: metric
- search:
    provider: duckduckgo
    target: _blank

- glances:
    url: http://192.168.3.11:61208
    version: 4 # required only if running glances v4 or higher, defaults to 3
    cpu: true # optional, enabled by default, disable by setting to false
    mem: true # optional, enabled by default, disable by setting to false
    cputemp: true # disabled by default
    uptime: true # disabled by default
    label: pve11 # optional