---

- PVE11:
    - PVE:
        icon: /icons/proxmox.png
        href: https://pve.d3adc3ii.cc
        ping: 192.168.2.11  
    - Opnsense:
        icon: /icons/opnsense.png
        href: https://opn.d3adc3ii.cc
        ping: 192.168.2.1  
       # widget:
       #     type: opnsense
       #     url: https://192.168.2.1:2184
       #     username: GUnKTSuel3+ueGnzOAabBh2Vp4XFucg1ffKDQU1odlvkpACnxjM2jU2K4MnUqTkKayXrpf3yJYCnaC9U
       #     password: 58G37tDa8tlbukEzlE9RcNn1DmIJZ76lGTvq/6dxQmP46Sazq1iI68s5pxbKGZtNVBnj0P5E9X3M4Jqq
    - DNS:
        icon: /icons/technitium.png
        href: https://dns.d3adc3ii.cc
        ping: 192.168.2.10
- PVE12:
    - Guacamole:
        icon: /icons/guacamole.png
        href: https://guaca.d3adc3ii.cc/guacamole
        ping: 192.168.2.20  
    - Homeassistant:
        icon: /icons/home-assistant.png
        href: https://ha.d3adc3ii.cc
        ping: 192.168.99.15  
    - Smokeping:
        icon: /icons/smokeping.png
        href: http://192.168.2.21/smokeping
        ping: 192.168.2.21  
    - pocketid:
        icon: /icons/pocket-id.png
        href: http://pocketid.d3adc3ii.cc
        ping: 192.168.2.16  
    - zabbix:
        icon: /icons/zabbix.png
        href: http://zabbix.d3adc3ii.cc/zabbix
        ping: 192.168.2.5  
    - checkmk:
        href: http://checkmk.d3adc3ii.cc
        ping: 192.168.2.17  
    - aria2:
        icon: /icons/ariang.png
        href: http://192.168.2.16:6880
        ping: 192.168.2.16 
    - wallos:
        icon: /icons/wallos.png
        href: http://wallos.d3adc3ii.cc
        ping: 192.168.2.19 
- PVE13:
    - Truenas: 
        icon: /icons/truenas-scale.png
        href: https://truenas.d3adc3ii.cc
        ping: 192.168.2.7
        widget:
            type: truenas
            url: https://192.168.2.7
            key: 1-zM5Mm8l4VdRa4WNybTWjVdHVM89TR7fkGj40DkYEPgFdkt83DYBea95J3SHe3uCe
            enablePools: true
            nasType: scale
    - Komodo:
        icon: /icons/komodo.png 
        href: https://komodo.d3adc3ii.cc
        ping: 192.168.2.23  
    - Qbit: 
        icon: /icons/qbittorrent.png
        href: https://qbit.d3adc3ii.cc
        ping: 192.168.2.22
        widget:
            type: qbittorrent
            #url: http://192.168.2.22:8090
            url: https://qbit.d3adc3ii.cc
            username: d3adc3ii
            password: WCxb2CcykoUmjiNAf3p8
            enableLeechProgress: true
    - Stash:
        icon: /icons/stash.png  
        href: https://stash.d3adc3ii.cc
        ping: 192.168.2.26  
        widget:
            type: stash
            url: https://stash.d3adc3ii.cc
            stashapikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJkMyIsInN1YiI6IkFQSUtleSIsImlhdCI6MTc0NjAzOTExOX0.OQqokQMNgdCRNxfPOQGOTFH4GCB0pQvZbIS9orkgkrg
    - PBS: 
        icon: /icons/proxmox.png
        href: https://pbs.d3adc3ii.cc
        ping: 192.168.2.30  
    - Karakeep: 
        icon: /icons/karakeep.png
        href: https://kara.d3adc3ii.cc
        widget:
            type: karakeep
            url: https://kara.d3adc3ii.cc
            key: ak1_0a2057e9b40f141217cf_8df52f0d56b037581ac4
    - Nexterm: 
        icon: /icons/nexterm.png
        href: https://nexterm.d3adc3ii.cc
- PVE12:
  - Info:
      href: https://pve11.d3adc3ii.cc
      ping: pve11.int.d3adc3ii.cc
      widget:
        type: glances
        url: http://192.168.3.13:61208
        version: 4
        metric: info
  - CPU:  
      href: https://pve11.d3adc3ii.cc
      ping: pve11.int.d3adc3ii.cc
        #  - CPU:
      widget:     
        type: glances
        url: http://192.168.3.11:61208
        version: 4
        metric: cpu
  - Memory:
      widget:     
        type: glances
        url: http://192.168.3.11:61208
        version: 4
        metric: memory
  - CPU Temp:
      widget:     
        type: glances
        url: http://192.168.3.11:61208
        version: 4
        metric: sensor:Composite
- PVE2:
  - Info:
      href: https://pve12.d3adc3ii.cc
      ping: pve12.int.d3adc3ii.cc
      widget:
        type: glances
        url: http://192.168.3.13:61208
        version: 4
        metric: info
  - CPU:  
      href: https://pve12.d3adc3ii.cc
      ping: pve12.int.d3adc3ii.cc
      widget:     
        type: glances
        url: http://192.168.3.12:61208
        version: 4
        metric: cpu
  - Memory:
      widget:     
        type: glances
        url: http://192.168.3.12:61208
        version: 4
        metric: memory
  - CPU Temp:
      widget:     
        type: glances
        url: http://192.168.3.12:61208
        version: 4
        metric: sensor:Composite
- PVE3:
  - Info:
      href: https://pve13.d3adc3ii.cc
      ping: pve13.int.d3adc3ii.cc
      widget:
        type: glances
        url: http://192.168.3.13:61208
        version: 4
        metric: info
  - CPU:
      widget:     
        type: glances
        url: http://192.168.3.13:61208
        version: 4
        metric: cpu
  - Memory:
      widget:     
        type: glances
        url: http://192.168.3.13:61208
        version: 4
        metric: memory
  - CPU Temp:
      widget:     
        type: glances
        url: http://192.168.3.13:61208
        version: 4
        metric: sensor:Composite

- Network:
    - Fortigate:
        icon: fortinet 
        href: http://fw.ntn.com.sg:7443 
    - FortiAnalyzer:
        icon: fortinet 
        href: http://faz.ntn.com.sg
    - FortiEMS:
        icon: fortinet
        href: http://ems.ntn.com.sg
    - Cisco:
        icon: cisco 
        href: http://10.203.1.254 
    - Synology:
        icon: synology 
        href: http://10.203.1.111:5000 
    - Crestron:
        icon: https://static.wixstatic.com/media/007dac_d97541360d5849a492f61055994b510e~mv2.png/v1/fill/w_281,h_281,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/007dac_d97541360d5849a492f61055994b510e~mv2.png
        href: http://10.203.2.125:5000 
    - Ruckus:
        icon: rundeck 
        href: http://10.203.7.200
- System:
    - Wordpress:
        icon: wordpress
        href: https://ntn.com.sg/wp-login.php