---

# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: d3 Homepage

backgorund: https://i.imgur.com/L2qaxsm.jpeg 
theme: dark
iconStyle: theme
target: _self
headerStyle: boxedWidgets 
layout:
  1st Tab:
    tab: Homelab

  PVE11:
    tab: Homelab
    style: row
    columns: 4
  PVE12:
    tab: Homelab
    style: row
    columns: 4
  PVE13:
    tab: Homelab
    style: row
    columns: 4
 # Monitor:
 #   tab: Homelab
 #   style: row
 #   columns: 4    
  Smarthome:
    tab: Homelab
    style: row
    columns: 4

  2nd Tab:
    tab: Monitor
  PVE1:
    tab: Monitor
    style: column
    columns: 3
  PVE2:
    tab: Monitor
    style: column
    columns: 3
  PVE3:
    tab: Monitor
    style: column
    columns: 3
  3rd Tab:
    tab: Corp
  Network:
    header: true
    tab: Corp
    style: row
    columns: 4  
  System:
    header: true
    tab: Corp
    style: row
    columns: 4  


