---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /
- openmeteo:
    label: Current
    latitude: 36.66
    longitude: -117.51
    cache: 5
- search:
    provider: duckduckgo
    target: _blank
