[SERVICE]
    Flush         60
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf
    Parsers_File  /fluent-bit/etc/parsers-custom.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*
    Path_Key          log.file.path
    DB                /var/fluent-bit/state/docker-logs.db
    DB.Sync           Normal
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Refresh_Interval  5

[FILTER]
    Name              parser
    Match             docker.*
    Key_Name          log.file.path
    Parser            docker_path
    Reserve_Data      On

[FILTER]
    Name              modify
    Match             docker.*
    Rename            container_id container.id

[FILTER]
    Name              record_modifier
    Match             *
    Record            stream_name komodo

[OUTPUT]
    Name              http
    Match             docker.*
    Host              10.10.10.53
    Port              9428
    URI               /insert/jsonline
    Format            json_lines
    Json_Date_Key     _time
    Json_Date_Format  iso8601
    Compress          gzip
    Header            VL-Msg-Field log
    Header            VL-Stream-Fields stream_name
