

##

[[stack]]
name = "blocky"
tags = ["komodo1"]
[stack.config]
server = "komodo1"
project_name = "blocky"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
file_contents = """
services:
  blocky:
    image: ghcr.io/0xerr0r/blocky
    container_name: blocky
    restart: unless-stopped
    # Optional the instance hostname for logging purpose
    hostname: blocky-hostname
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/udp"
      - "853:853/tcp"
      - "4000:4000/tcp"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Singapore # Optional to synchronize the log timestamp with host
      - CDATA=/mnt/cephfs/appdata
    volumes:
      # Optional to synchronize the log timestamp with host
      - /etc/localtime:/etc/localtime:ro
      # config file
      - ${CDATA}/blocky/config.yml:/app/config.yml:ro
      - ${ZDATA}/blocky/logs:/logs
      - ${ZDATA}/blocky/denylists:/app/denylists/
      - ${ZDATA}/blocky/allowlists:/app/allowlists/
"""
environment = """
CDATA=/mnt/cephfs/appdata
"""

##
HOMEPAGE_VAR_JELLY_ENABLEBLOCK=true
HOMEPAGE_VAR_JELLY_NOWPLAY=false

# Immich
HOMEPAGE_VAR_IMMICH_ICON = "/icons/immich-light.png"
HOMEPAGE_VAR_IMMICH_URL= "https://immich.d3hl.site"
HOMEPAGE_VAR_IMMICH_KEY=W7IJnjVEIhc7d72AAm4sxJ49YJI1kdtkiVvmCZipVqc
HOMEPAGE_VAR_IMMICH_VERSION= 2
HOMEPAGE_VAR_IMMICH_FIELDS= ["storage","photos","videos"] 
# Stash
HOMEPAGE_VAR_STASH_ICON= "/icons/stash-light.png"
HOMEPAGE_VAR_STASH_URL= "https://stash.d3adc3ii.site"
HOMEPAGE_VAR_STASH_USER= "d3adc3ii"
HOMEPAGE_VAR_QBIT_API= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJkMyIsInN1YiI6IkFQSUtleSIsImlhdCI6MTc0NjAzOTExOX0.OQqokQMNgdCRNxfPOQGOTFH4GCB0pQvZbIS9orkgkrg"

#### ACCESS ####################################################################################################################################################################################################
# Guacamole
HOMEPAGE_VAR_GUACAMOLE_ICON= "/icons/apache-guacamole-light.png"
HOMEPAGE_VAR_GUACAMOLE_URL= "https://guaca.d3adc3ii.site/guacamole"
HOMEPAGE_VAR_GUACAMOLEEXT_URL= "https://guaca.d3adc3ii.cc/guacamole"
# SHELLHUB
HOMEPAGE_VAR_SHELLHUB_ICON= "sh-shellhub-light"
HOMEPAGE_VAR_SHELLHUB_URL= "http://192.168.2.33"

#### LOGGING ####################################################################################################################################################################################################
# Grafana
HOMEPAGE_VAR_GRAFANA_ICON= "/icons/grafana-light.png"
HOMEPAGE_VAR_GRAFANA_URL= "https://d3adc3ii.grafana.net/dashboards"
HOMEPAGE_VAR_GRAFANA_URL= "https://grafana.d3adc3ii.cc"
HOMEPAGE_VAR_GRAFANAC_URL= "https://grafana.d3adc3ii.cc/d/n5bu_kv45/traefik-official-standalone-dashboard"


HOMEPAGE_VAR_INFLUX_ICON= "sh-influx-light"
HOMEPAGE_VAR_INFLUX_URL= "https://influxdb.d3adc3ii.site"
# Scutiny
HOMEPAGE_VAR_SCRUTINY_ICON= "/icons/scrutiny-light.png"
HOMEPAGE_VAR_SCRUTINY_URL= "https://scrutiny.d3adc3ii.cc" 
# Dozzle
HOMEPAGE_VAR_DOZZLE_ICON= "sh-dozzle-light"
HOMEPAGE_VAR_DOZZLE_URL= "https://dozzle.d3adc3ii.site"
# Pulse
HOMEPAGE_VAR_PULSEXT_ICON= "sh-proxmox-light"
HOMEPAGE_VAR_PULSEXT_URL= "https://pulse.d3adc3ii.cc"

#### APPS ####################################################################################################################################################################################################
# Actual Budget
HOMEPAGE_VAR_ACTUAL_ICON= "sh-actual-budget-light"
HOMEPAGE_VAR_ACTUAL_URL= "https://actual.d3adc3ii.site"
# Sensei
HOMEPAGE_VAR_SENSEI_ICON= "sh-sentry-light"
HOMEPAGE_VAR_SENSEI_URL= "https://statement.d3adc3ii.site"
# Semaphore
HOMEPAGE_VAR_SEMAPHORE_ICON= "/icons/semaphore-ui-light.png"
HOMEPAGE_VAR_SEMAPHORE_URL= "https://semaphore.d3adc3ii.site"
# Aria2
HOMEPAGE_VAR_ARIA_ICON= "sh-aria2-light"
HOMEPAGE_VAR_ARIA_URL= "https://dl.d3adc3ii.site"
# NZBGET
HOMEPAGE_VAR_NZBGET_ICON= "sh-nzbget-light"
HOMEPAGE_VAR_NZBGET_URL= "https://nzbget.d3adc3ii.site"
# Karakeep
HOMEPAGE_VAR_KARAKEEP_ICON= "/icons/karakeep.png"
HOMEPAGE_VAR_KARAKEEP_URL= "https://kara.d3adc3ii.cc"
# Wallos
HOMEPAGE_VAR_WALLOS_ICON= "/icons/wallos-light.png"
HOMEPAGE_VAR_WALLOS_URL= "https://wallos.d3adc3ii.cc"
# Ommni Tools
HOMEPAGE_VAR_OMNITOOLS_ICON= "sh-omnitools-light"
HOMEPAGE_VAR_OMNITOOLS_URL= "https://omnitools.d3adc3ii.cc"

#### TOOLS ####################################################################################################################################################################################################

#### EXTRAS ####################################################################################################################################################################################################
# Selfhst-icons
HOMEPAGE_VAR_SELFHST_ICON= "sh-selfh-st-light" 
HOMEPAGE_VAR_SELFHST_URL= "https://selfhst-icons.d3adc3ii.cc"

###################   CORP    ##################### 

# Komodo
HOMEPAGE_VAR_KOMODOCORP_URL="http://10.203.1.121:9120"
# Fenrus
HOMEPAGE_VAR_FENRUS_ICON="sh-fenrus"
HOMEPAGE_VAR_FENRUS_URL="http://10.203.1.120:3222"
# PVECORP
HOMEPAGE_VAR_PVECORP_URL="https://10.203.1.113:8006"
# UNIMUS  
HOMEPAGE_VAR_UNIMUS_ICON="sh-unimus-light"
HOMEPAGE_VAR_UNIMUS_URL="http://10.203.1.120:8085"

### GL1 ###
# PVE11
HOMEPAGE_VAR_PVE11_URL= "https://pve11.d3adc3ii.cc"
HOMEPAGE_VAR_PVE12_URL= "10.10.10.12"
HOMEPAGE_VAR_PVE13_URL= "10.10.10.13"
HOMEPAGE_VAR_GLANCES_PVE11= "http://10.10.10.11:61208"
HOMEPAGE_VAR_GLANCES_PVE12= "http://10.10.10.12:61208"
HOMEPAGE_VAR_GLANCES_PVE13= "http://10.10.10.13:61208"
"""