- _hidden0:
    - TPlink:
      - icon: /icons/services/unraid.png
        href: http://example.local:8090/Dashboard

    - Proton:
      - icon: sh-proton
        href: https://mail.proton.me/u/4/inbox