my-docker:
  host: socket-proxy
  port: 2375
komodo-3:
  host: 10.10.10.27
  port: 2376
  tls:
    keyFile: tls/server-key.pem
    caFile: tls/ca.pem
    certFile: tls/server-cert.pem
  #port: 443
  #protocol: https