---
- Internal:
    - Nas:
        -  Truenas: 
            icon: /icons/truenas-scale.png
            href: https://192.168.2.7
            ping: 192.168.2.7
            widget:
                type: truenas
                url: https://192.168.2.7
                key: 1-zM5Mm8l4VdRa4WNybTWjVdHVM89TR7fkGj40DkYEPgFdkt83DYBea95J3SHe3uCe
                enablePools: true
                nasType: scale
    - Pve: # proxmoxx
        - pve11:
            icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
            href: {{HOMEPAGE_VAR_PROXMOX_URL_PVE_1}}
            sitemonitor: {{HOMEPAGE_VAR_PROXMOX_URL_PVE_1}}
        - PBS: 
            icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
            href: {{HOMEPAGE_VAR_PBS_URL}}
            sitemonitor: {{HOMEPAGE_VAR_PBS_URL}} 
    - M0nit0ring:
        - NetAlertX:
            icon: {{HOMEPAGE_VAR_NETALERTX_ICON}}
            href: {{HOMEPAGE_VAR_NETALERTX_URL}}
            sitemonitor: {{HOMEPAGE_VAR_NETALERTX_URL}}
        - Smokeping:
            icon: {{HOMEPAGE_VAR_SMOKEPING_ICON}}
            href: {{HOMEPAGE_VAR_SMOKEPING_URL}}
            sitemonitor: {{HOMEPAGE_VAR_SMOKEPING_URL}}
        - Guacamole:
            icon: {{HOMEPAGE_VAR_GUACAMOLE_ICON}} 
            href: {{HOMEPAGE_VAR_GUACAMOLE_URL}}
            sitemonitor: {{HOMEPAGE_VAR_GUACAMOLE_URL}}
        - Battle of the badwidth:
            icon: {{HOMEPAGE_VAR_BOTB_ICON}}
            href: {{HOMEPAGE_VAR_BOTB_URL}}
    - I1: 
        - Opnsense:
            icon: {{HOMEPAGE_VAR_OPNSENSE_ICON}} 
            href: {{HOMEPAGE_VAR_OPNSENSE_URL}}
            sitemonitor: {{HOMEPAGE_VAR_OPNSENSE_URL}}
        - DNS:
            icon: {{HOMEPAGE_VAR_DNS_ICON}}
            href: {{HOMEPAGE_VAR_DNS_URL}}
            sitemonitor: {{HOMEPAGE_VAR_DNS_URL}}
    - Media:
        - Jellyfin:
            icon: {{HOMEPAGE_VAR_JELLY_ICON}}
            href: {{HOMEPAGE_VAR_JELLY_URL}}
            sitemonitor: {{HOMEPAGE_VAR_JELLY_URL}}
        - Immich:
            icon: {{HOMEPAGE_VAR_IMMICH_ICON}} 
            href: {{HOMEPAGE_VAR_IMMICH_URL}}
            sitemonitor: {{HOMEPAGE_VAR_IMMICH_URL}}
            widget:
                type: immich
                url: {{HOMEPAGE_VAR_IMMICH_URL}} 
                key: {{HOMEPAGE_VAR_IMMICH_KEY}}
                version: {{HOMEPAGE_VAR_IMMICH_VERSION}}
                fields:  {{HOMEPAGE_VAR_IMMICH_FIELDS}}  
    - Local Apps: # remote
        - Actual:
            icon: {{HOMEPAGE_VAR_ACTUAL_ICON}}
            href: {{HOMEPAGE_VAR_ACTUAL_URL}}
        - SteamentSensei:
            icon: {{HOMEPAGE_VAR_SENSEI_ICON}}
            href: {{HOMEPAGE_VAR_SENSEI_URL}} 
            sitemonitor: {{HOMEPAGE_VAR_SENSEI_URL}}
        - Homeassistant:
            icon: {{HOMEPAGE_VAR_HA_ICON}}
            href: {{HOMEPAGE_VAR_HA_URL}}
            sitemonitor: {{HOMEPAGE_VAR_HA_URL}}
        - Sh:
            icon: {{HOMEPAGE_VAR_STASH_ICON}}
            href: {{HOMEPAGE_VAR_STASH_URL}}
            sitemonitor: {{HOMEPAGE_VAR_STASH_URL}}
            widget:
                type: stash
                url: {{HOMEPAGE_VAR_STASH_URL}}
                stashapikey: {{HOMEPAGE_VAR_STASH_API}}
        - Semaphore:
            icon: {{HOMEPAGE_VAR_SEMAPHORE_ICON}}
            href: {{HOMEPAGE_VAR_SEMAPHORE_URL}}
            sitemonitor: {{HOMEPAGE_VAR_SEMAPHORE_URL}}
        - aria2:
            icon: {{HOMEPAGE_VAR_ARIA_ICON}}
            href: {{HOMEPAGE_VAR_ARIA_URL}}
            sitemonitor: {{HOMEPAGE_VAR_ARIA_URL}}
