- Infra Core:
    - PVE:
        icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
        href: {{HOMEPAGE_VAR_PROXMOX_URL_PVE11}}
        sitemonitor: {{HOMEPAGE_VAR_PROXMOX_URL_PVE11}}
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PROXMOX_IP_PVE11}}
            username: {{HOMEPAGE_VAR_PROXMOX_USER}}
           # password: {{HOMEPAGE_VAR_PROXMOX_SECRET}}
            password: 8cc78ffc-dd21-438f-8787-e4ab2ca48a16 
            node: pve11
    -  Truenas:
        id: truenas 
        icon: {{HOMEPAGE_VAR_TRUENAS_ICON}}
        href: {{HOMEPAGE_VAR_TRUENAS_URL}}
        sitemonitor: {{HOMEPAGE_VAR_TRUENAS_URL}}
        widget:
            type: truenas
            url: {{HOMEPAGE_VAR_TRUENAS_URL}}
            key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
            enablePools: {{HOMEPAGE_VAR_TRUENAS_ENABLEDPOOL}}
            nasType: scale
    - Komodo:
        icon: {{HOMEPAGE_VAR_KOMODO_ICON}} 
        href: {{HOMEPAGE_VAR_KOMODO_URL}}
        sitemonitor: {{HOMEPAGE_VAR_KOMODO_URL}}
        widget:
            type: komodo
            url: {{HOMEPAGE_VAR_KOMODO_IPURL}}
            key: {{HOMEPAGE_VAR_KOMODO_KEY}}
            secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
            showSummary: true # optional, default: false
            showStacks: true # optional, default: false
    - Homeassistant:
        icon: {{HOMEPAGE_VAR_HA_ICON}}
        href: {{HOMEPAGE_VAR_HA_URL}}
        sitemonitor: {{HOMEPAGE_VAR_HA_URL}}
########################################################################################################################################################################################################
- Domain:
    - Authentik:
        icon: {{HOMEPAGE_VAR_AUTHENTIK_ICON}}
        href: {{HOMEPAGE_VAR_AUTHENTIK_URL}}
        sitemonitor: {{HOMEPAGE_VAR_AUTHENTIK_URL}}
        widget:
            type: authentik
            url: {{HOMEPAGE_VAR_AUTHENTIK_URL}}
            key: {{HOMEPAGE_VAR_AUTHENTIK_KEY}} 
    - Technitium:
        icon: {{HOMEPAGE_VAR_DNS_ICON}}
        href: {{HOMEPAGE_VAR_DNS_URL}}
        ping: {{HOMEPAGE_VAR_DNS_URL}}
        widget:
            type: technitium
            url: {{HOMEPAGE_VAR_DNS_URL}}
            key: {{HOMEPAGE_VAR_DNS_KEY}}
            range: {{HOMEPAGE_VAR_DNS_RANGE}}
    - GoDoxy:
        icon: {{HOMEPAGE_VAR_GODOXY_ICON}}
        href: {{HOMEPAGE_VAR_GODOXY_URL}} 
        ping: {{HOMEPAGE_VAR_GODOXY_URL}}
    - Pangolin:
        icon: {{HOMEPAGE_VAR_PANGOLIN_ICON}}
        href: {{HOMEPAGE_VAR_PANGOLIN_URL}}
        sitemonitor: {{HOMEPAGE_VAR_PANGOLIN_URL}}
########################################################################################################################################################################################################
- Network:
    - NetAlertX:
        icon: {{HOMEPAGE_VAR_NETALERTX_ICON}}
        href: {{HOMEPAGE_VAR_NETALERTX_URL}}
        ping: {{HOMEPAGE_VAR_NETALERTX_URL}}
        widget:
            type: netalertx
            key: {{HOMEPAGE_VAR_NETALERTX_KEY}}
            url: {{HOMEPAGE_VAR_NETALERTX_URL}}
            fields: {{HOMEPAGE_VAR_NETALERTX_FIELDS}}
    - Uptime-Kuma:
        icon: {{HOMEPAGE_VAR_KUMA_ICON}}
        href: {{HOMEPAGE_VAR_KUMA_URL}}
        widget:
            type: uptimekuma
            url: {{HOMEPAGE_VAR_KUMA_URL}}
            slug: ping
    - PHPIPAM:
        icon: {{HOMEPAGE_VAR_PHPIPAM_ICON}}
        href: {{HOMEPAGE_VAR_PHPIPAM_URL}}
########################################################################################################################################################################################################
- Monitor:
    - Speedtest:
        icon: {{HOMEPAGE_VAR_SPEEDTEST_ICON}}
        href: {{HOMEPAGE_VAR_SPEEDTEST_URL}}
        widget:
            type: speedtest
            url: {{HOMEPAGE_VAR_SPEEDTEST_URL}}
            version: 2
            key: {{HOMEPAGE_VAR_SPEEDTEST_KEY}}
    - Beszel:
        icon: {{HOMEPAGE_VAR_BESZEL_ICON}} 
        href: {{HOMEPAGE_VAR_BESZEL_URL}}
        sitemonitor: {{HOMEPAGE_VAR_BESZEL_URL}}
        widget:
            type: beszel
            #url: https://beszel.d3hl.cc
            url: http://10.10.10.9:8090
            username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
            password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}} 
            version: {{HOMEPAGE_VAR_BESZEL_VERSION}}
            bitratePrecision: 3 # optional, default is 0        
    - Wazuh:
        icon: {{HOMEPAGE_VAR_WAZUH_ICON}}
        href: {{HOMEPAGE_VAR_WAZUH_URL}}
        ping: {{HOMEPAGE_VAR_WAZUH_URL}}
    - Dozzle:
        icon: {{HOMEPAGE_VAR_DOZZLE_ICON}}
        href: {{HOMEPAGE_VAR_DOZZLE_URL}}
    - Apprise-API:
        icon: {{HOMEPAGE_VAR_APPRISE_ICON}}
        href: {{HOMEPAGE_VAR_APPRISE_URL}}
        sitemonitor: {{HOMEPAGE_VAR_APPRISE_URL}}
    - Healthcheck:
        icon: {{HOMEPAGE_VAR_HEALTHCHECKS_ICON}}
        href: {{HOMEPAGE_VAR_HEALTHCHECKS_URL}}
        sitemonitor: {{HOMEPAGE_VAR_HEALTHCHECKS_URL}}
    - Smokeping:
        icon: {{HOMEPAGE_VAR_SMOKEPING_ICON}}
        href: {{HOMEPAGE_VAR_SMOKEPING_URL}}
        sitemonitor: {{HOMEPAGE_VAR_SMOKEPING_URL}}
########################################################################################################################################################################################################
- Backup: 
    - PBS: 
        icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
        href: {{HOMEPAGE_VAR_PBS_URL}}
        ping: {{HOMEPAGE_VAR_PBS_URL}} 
        widget:
            type: proxmoxbackupserver
            url: {{HOMEPAGE_VAR_PBS_URL}} 
            username: {{HOMEPAGE_VAR_PBS_USER}}
            password: {{HOMEPAGE_VAR_PBS_SECRET}}
            #datastore: datastore_name #optional; if ommitted, will display a combination of all datastores used / total    
    - Backrest:
        icon: {{HOMEPAGE_VAR_BACKREST_ICON}}
        href: {{HOMEPAGE_VAR_BACKREST_URL}}
        ping: {{HOMEPAGE_VAR_BACKREST_URL}}
    - remote-backups:
        icon: {{HOMEPAGE_VAR_REMOTEBACKUP_ICON}}
        href: {{HOMEPAGE_VAR_REMOTEBACKUP_URL}}
########################################################################################################################################################################################################
- Media:
    - Jellyfin:
        icon: {{HOMEPAGE_VAR_JELLY_ICON}}
        href: {{HOMEPAGE_VAR_JELLY_URL}}
        ping: {{HOMEPAGE_VAR_JELLY_URL}}
        widget:
            type: jellyfin
            url: {{HOMEPAGE_VAR_JELLY_URL}} 
            key: {{HOMEPAGE_VAR_JELLY_KEY}}
            enableBlock: {{HOMEPAGE_VAR_JELLY_ENABLEBLOCK}}
            enableNowPlaying: {{HOMEPAGE_VAR_JELLY_NOWPLAY}}
    - Immich:
        icon: {{HOMEPAGE_VAR_IMMICH_ICON}} 
        href: {{HOMEPAGE_VAR_IMMICH_URL}}
        sitemonitor: {{HOMEPAGE_VAR_IMMICH_URL}}
        widget:
            type: immich
            url: {{HOMEPAGE_VAR_IMMICH_URL}} 
            key: {{HOMEPAGE_VAR_IMMICH_KEY}}
            version: {{HOMEPAGE_VAR_IMMICH_VERSION}}
            fields:  {{HOMEPAGE_VAR_IMMICH_FIELDS}}  
    - Sh:
        icon: {{HOMEPAGE_VAR_STASH_ICON}}
        href: {{HOMEPAGE_VAR_STASH_URL}}
        sitemonitor: {{HOMEPAGE_VAR_STASH_URL}}
        widget:
            type: stash
            url: {{HOMEPAGE_VAR_STASH_URL}}
            stashapikey: {{HOMEPAGE_VAR_STASH_API}}
########################################################################################################################################################################################################
- Access:
    - Guacamole (External):
        icon: {{HOMEPAGE_VAR_GUACAMOLE_ICON}} 
        href: {{HOMEPAGE_VAR_GUACAMOLEEXT_URL}}
        sitemonitor: {{HOMEPAGE_VAR_GUACAMOLEEXT_URL}}
    - Guacamole:
        icon: {{HOMEPAGE_VAR_GUACAMOLE_ICON}} 
        href: {{HOMEPAGE_VAR_GUACAMOLE_URL}}
        sitemonitor: {{HOMEPAGE_VAR_GUACAMOLE_URL}}
    - Dumbterm:
        icon: {{HOMEPAGE_VAR_DUMBTERM_ICON}}
        href: {{HOMEPAGE_VAR_DUMBTERM_URL}}
        sitemonitor: {{HOMEPAGE_VAR_DUMBTERM_URL}}
    - Shellhub:
        icon: {{HOMEPAGE_VAR_SHELLHUB_ICON}}
        href: {{HOMEPAGE_VAR_SHELLHUB_URL}}
    - Termix:
        icon: {{HOMEPAGE_VAR_TERMIX_ICON}}
        href: {{HOMEPAGE_VAR_TERMIX_URL}}
########################################################################################################################################################################################################
- Troubleshoot: 
    - Dozzle:
        icon: {{HOMEPAGE_VAR_DOZZLE_ICON}}
        href: {{HOMEPAGE_VAR_DOZZLE_URL}}
########################################################################################################################################################################################################
- Appplications:
    - Actual:
        icon: {{HOMEPAGE_VAR_ACTUAL_ICON}}
        href: {{HOMEPAGE_VAR_ACTUAL_URL}}
    - SteamentSensei:
        icon: {{HOMEPAGE_VAR_SENSEI_ICON}}
        href: {{HOMEPAGE_VAR_SENSEI_URL}} 
        sitemonitor: {{HOMEPAGE_VAR_SENSEI_URL}}
    - Semaphore:
        icon: {{HOMEPAGE_VAR_SEMAPHORE_ICON}}
        href: {{HOMEPAGE_VAR_SEMAPHORE_URL}}
        sitemonitor: {{HOMEPAGE_VAR_SEMAPHORE_URL}}
    - aria2:
        icon: {{HOMEPAGE_VAR_ARIA_ICON}}
        href: {{HOMEPAGE_VAR_ARIA_URL}}
        sitemonitor: {{HOMEPAGE_VAR_ARIA_URL}}
    - nzbget:
        icon: {{HOMEPAGE_VAR_NZBGET_ICON}}
        href: {{HOMEPAGE_VAR_NZBGET_URL}}
        ping: {{HOMEPAGE_VAR_NZBGET_URL}}
    - Karakeep:
        icon: {{HOMEPAGE_VAR_KARAKEEP_ICON}}
        href: {{HOMEPAGE_VAR_KARAKEEP_URL}}
        sitemonitor: {{HOMEPAGE_VAR_KARAKEEP_URL}}
    - wallos:
        icon: {{HOMEPAGE_VAR_WALLOS_ICON}} 
        href: {{HOMEPAGE_VAR_WALLOS_URL}}
        sitemonitor: {{HOMEPAGE_VAR_WALLOS_URL}}
    - Omni-tools:
        icon: {{HOMEPAGE_VAR_OMNITOOLS_ICON}} 
        href: {{HOMEPAGE_VAR_OMNITOOLS_URL}}
        sitemonitor: {{HOMEPAGE_VAR_OMNITOOLS_URL}}
########################################################################################################################################################################################################
- Tools:
    - Grafana on:
        icon: {{HOMEPAGE_VAR_GRAFANA_ICON}}
        href: {{HOMEPAGE_VAR_GRAFANAPANGOLIN_URL}}
    - Grafana:
        icon: {{HOMEPAGE_VAR_GRAFANA_ICON}}
        href: {{HOMEPAGE_VAR_GRAFANA_URL}}
    - Scrutiny:
        icon: {{HOMEPAGE_VAR_SCRUTINY_ICON}}
        href: {{HOMEPAGE_VAR_SCRUTINY_URL}}
    - Pulse:
        icon: {{HOMEPAGE_VAR_PULSEXT_ICON}}
        href: {{HOMEPAGE_VAR_PULSEXT_URL}}
    - zabbix:
        icon: {{HOMEPAGE_VAR_ZABBIX_ICON}} 
        href: {{HOMEPAGE_VAR_ZABBIX_URL}}
        sitemonitor: {{HOMEPAGE_VAR_ZABBIX_URL}}
    - checkmk:
        icon: {{HOMEPAGE_VAR_CHECKMK_ICON}}
        href: {{HOMEPAGE_VAR_CHECKMK_URL}}
        sitemonitor: {{HOMEPAGE_VAR_CHECKMK_URL}}
    - Netbox Cloud:
        icon: {{HOMEPAGE_VAR_NETBOX_ICON}}
        href: {{HOMEPAGE_VAR_NETBOXCL_URL}}
    - Netbox Console:
        icon: {{HOMEPAGE_VAR_NETBOX_ICON}}
        href: {{HOMEPAGE_VAR_NETBOXCS_URL}}
    - Nautobox:
        icon: {{HOMEPAGE_VAR_NAUTOBOT_ICON}}
        href: {{HOMEPAGE_VAR_NAUTOBOT_URL}}
########################################################################################################################################################################################################
- Extras:
    - Selfhst-icons:
        icon: {{HOMEPAGE_VAR_SELFHST_ICON}} 
        href: {{HOMEPAGE_VAR_SELFHST_URL}}

########################################################################################################################################################################################################
### CORP TAB ###    
- Office Core:
    - PVECORP:
        icon: {{HOMEPAGE_VAR_PROXMOX_ICON}} 
        href: {{HOMEPAGE_VAR_PVECORP_URL}} 
    - Komodocorp:
        icon: {{HOMEPAGE_VAR_KOMODO_ICON}} 
        href: {{HOMEPAGE_VAR_KOMODOCORP_URL}} 
    - Fenrus:
        icon: {{HOMEPAGE_VAR_FENRUS_ICON}} 
        href: {{HOMEPAGE_VAR_FENRUS_URL}} 
- Corp Systems:
    - Wordpress:
        icon: wordpress
        href: https://ntn.com.sg/wp-login.php
########################################################################################################################################################################################################
### CLOUD TAB ###        
- Corp Network:
    - Fortigate:
        icon: fortinet 
        href: http://fw.ntn.com.sg:7443 
    - FortiAnalyzer:
        icon: fortinet 
        href: http://faz.ntn.com.sg
    - FortiEMS:
        icon: fortinet
        href: http://ems.ntn.com.sg
    - Cisco:
        icon: cisco 
        href: http://10.203.1.254/webui 
    - Synology:
        icon: synology 
        href: http://10.203.1.111:5000 
    - Crestron:
        icon: https://static.wixstatic.com/media/007dac_d97541360d5849a492f61055994b510e~mv2.png/v1/fill/w_281,h_281,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/007dac_d97541360d5849a492f61055994b510e~mv2.png
        href: http://10.203.7.125
    - Ruckus:
        icon: rundeck 
        href: http://10.203.6.200
########################################################################################################################################################################################################
### CLOUD TAB ###        
- Corp Cloud:
    - Intune:
        icon: /icons/microsoft-365.png 
        href: https://intune.microsoft.com
    - Entra:
        icon: /icons/microsoft-365.png
        href: https://entra.microsoft.com
    - Azure Portal:
        icon: /icons/azure.png
        href: https://portal.azure.com
    - AzureDevOps:
        icon: /icons/azure-devops.png 
        href: https://dev.azure.com/ntnsg/intune
    