- Infra Core:
    - PVE:
        icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
        href: {{HOMEPAGE_VAR_PROXMOX_URL_PVE_1}}
        sitemonitor: {{HOMEPAGE_VAR_PROXMOX_URL_PVE_1}}
        ping: {{HOMEPAGE_VAR_PROXMOX_URL_PVE_1}}
        widget:
            type: beszel
            url: http://10.10.10.9:8090
            username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
            password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}} 
            version: {{HOMEPAGE_VAR_BESZEL_VERSION}}
            systemId: {{HOMEPAGE_VAR_BESZEL_SYSTEMID_pve11}}
            fields: {{HOMEPAGE_VAR_BESZEL_FIELDS}}
    -  Truenas:
        id: truenas 
        icon: {{HOMEPAGE_VAR_TRUENAS_ICON}}
        href: {{HOMEPAGE_VAR_TRUENAS_URL}}
        sitemonitor: {{HOMEPAGE_VAR_TRUENAS_URL}}
        widget:
            type: truenas
            url: {{HOMEPAGE_VAR_TRUENAS_URL}}
            key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
            enablePools: {{HOMEPAGE_VAR_TRUENAS_ENABLEDPOOL}}
            nasType: scale
    - Komodo:
        icon: {{HOMEPAGE_VAR_KOMODO_ICON}} 
        href: {{HOMEPAGE_VAR_KOMODO_URL}}
        sitemonitor: {{HOMEPAGE_VAR_KOMODO_URL}}
        widget:
            type: komodo
            url:  {{HOMEPAGE_VAR_KOMODO_API_URL}}
            key: {{HOMEPAGE_VAR_KOMODO_KEY}}
            secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
            showSummary: true # optional, default: false
            showStacks: true # optional, default: false
    - Homeassistant:
        icon: {{HOMEPAGE_VAR_HA_ICON}}
        href: {{HOMEPAGE_VAR_HA_URL}}
        sitemonitor: {{HOMEPAGE_VAR_HA_URL}}