---
- Internal:
    - Nas:
        -  Truenas:
            id: truenas 
            icon: {{HOMEPAGE_VAR_TRUENAS_ICON}}
            href: {{HOMEPAGE_VAR_TRUENAS_URL}}
            sitemonitor: {{HOMEPAGE_VAR_TRUENAS_URL}}
            widget:
                type: truenas
                url: {{HOMEPAGE_VAR_TRUENAS_URL}}
                key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
                enablePools: {{HOMEPAGE_VAR_TRUENAS_ENABLEDPOOL}}
                nasType: scale
    - Pve: # proxmoxx
        - pve11:
            icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
            href: {{HOMEPAGE_VAR_PROXMOX_URL_PVE_1}}
            sitemonitor: {{HOMEPAGE_VAR_PROXMOX_URL_PVE_1}}
            ping: {{HOMEPAGE_VAR_PROXMOX_URL_PVE_1}}
            widget:
                type: beszel
                url: http://10.10.10.9:8090
                username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
                password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}} 
                version: {{HOMEPAGE_VAR_BESZEL_VERSION}}
                systemId: {{HOMEPAGE_VAR_BESZEL_SYSTEMID_pve11}}
                fields: {{HOMEPAGE_VAR_BESZEL_FIELDS}}
        - pve12:
            icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
            ping: {{HOMEPAGE_VAR_PROXMOX_URL_PVE_2}}
            widget:
                type: beszel
                url: http://10.10.10.9:8090
                username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
                password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}} 
                version: {{HOMEPAGE_VAR_BESZEL_VERSION}}
                systemId: {{HOMEPAGE_VAR_BESZEL_SYSTEMID_pve12}}
                fields: {{HOMEPAGE_VAR_BESZEL_FIELDS}}
        - pve13:
            ping: {{HOMEPAGE_VAR_PROXMOX_URL_PVE_3}}
            icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
            widget:
                type: beszel
                url: http://10.10.10.9:8090
                username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
                password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}} 
                version: {{HOMEPAGE_VAR_BESZEL_VERSION}}
                systemId: {{HOMEPAGE_VAR_BESZEL_SYSTEMID_pve13}}
                fields: {{HOMEPAGE_VAR_BESZEL_FIELDS}}
        - PBS: 
            icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
            href: {{HOMEPAGE_VAR_PBS_URL}}
            ping: {{HOMEPAGE_VAR_PBS_URL}} 
            widget:
                type: beszel
                url: http://10.10.10.9:8090
                username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
                password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}} 
                version: {{HOMEPAGE_VAR_BESZEL_VERSION}}
                systemId: {{HOMEPAGE_VAR_BESZEL_SYSTEMID_pbs}}
                fields: {{HOMEPAGE_VAR_BESZEL_FIELDS}}
    - Local:        
        - Opnsense:
            icon: {{HOMEPAGE_VAR_OPNSENSE_ICON}} 
            href: {{HOMEPAGE_VAR_OPNSENSE_URL}}
            sitemonitor: {{HOMEPAGE_VAR_OPNSENSE_URL}}
        - Mikrotik:
            icon: {{HOMEPAGE_VAR_MIKROTIK_ICON}} 
            href: {{HOMEPAGE_VAR_MIKROTIK_URL}}
            sitemonitor: {{HOMEPAGE_VAR_MIKROTIK_URL}}
        - Tplink:
            icon: {{HOMEPAGE_VAR_TPLINK_ICON}} 
            href: {{HOMEPAGE_VAR_TPLINK_URL}}
            sitemonitor: {{HOMEPAGE_VAR_TPLINK_URL}}
    - DNS:
        - NetAlertX:
            icon: {{HOMEPAGE_VAR_NETALERTX_ICON}}
            href: {{HOMEPAGE_VAR_NETALERTX_URL}}
            ping: {{HOMEPAGE_VAR_NETALERTX_URL}}
            widget:
                type: netalertx
                key: {{HOMEPAGE_VAR_NETALERTX_KEY}}
                url: {{HOMEPAGE_VAR_NETALERTX_URL}}
                fields: {{HOMEPAGE_VAR_NETALERTX_FIELDS}}
        - Technitium:
            icon: {{HOMEPAGE_VAR_DNS_ICON}}
            href: {{HOMEPAGE_VAR_DNS_URL}}
            ping: {{HOMEPAGE_VAR_DNS_URL}}
            widget:
                type: technitium
                url: {{HOMEPAGE_VAR_DNS_URL}}
                key: {{HOMEPAGE_VAR_DNS_KEY}}
                range: {{HOMEPAGE_VAR_DNS_RANGE}}
        - Speedtest:
            icon: {{HOMEPAGE_VAR_SPEEDTEST_ICON}}
            href: {{HOMEPAGE_VAR_SPEEDTEST_URL}}
     #   - CaddyProxy:
      #      icon: {{HOMEPAGE_VAR_CADDYPROXY_ICON}} 
      #      ping: {{HOMEPAGE_VAR_CADDYPROXY_URL}}
       #     widget:
        #        type: caddy
         #       url: {{HOMEPAGE_VAR_CADDYPROXY_URL}}
    - Internal Monitor:
        - GoDoxy:
            icon: {{HOMEPAGE_VAR_GODOXY_ICON}}
            href: {{HOMEPAGE_VAR_GODOXY_URL}} 
            ping: {{HOMEPAGE_VAR_GODOXY_URL}}
        - Wazuh:
            icon: {{HOMEPAGE_VAR_WAZUH_ICON}}
            href: {{HOMEPAGE_VAR_WAZUH_URL}}
            ping: {{HOMEPAGE_VAR_WAZUH_URL}}
        - Dozzle:
            icon: {{HOMEPAGE_VAR_DOZZLE_ICON}}
            href: {{HOMEPAGE_VAR_DOZZLE_URL}}
        - Apprise-API:
            icon: {{HOMEPAGE_VAR_APPRISE_ICON}}
            href: {{HOMEPAGE_VAR_APPRISE_URL}}
            sitemonitor: {{HOMEPAGE_VAR_APPRISE_URL}}
        - Healthcheck:
            icon: {{HOMEPAGE_VAR_HEALTHCHECKS_ICON}}
            href: {{HOMEPAGE_VAR_HEALTHCHECKS_URL}}
            sitemonitor: {{HOMEPAGE_VAR_HEALTHCHECKS_URL}}
        - Smokeping:
            icon: {{HOMEPAGE_VAR_SMOKEPING_ICON}}
            href: {{HOMEPAGE_VAR_SMOKEPING_URL}}
            sitemonitor: {{HOMEPAGE_VAR_SMOKEPING_URL}}
        - Guacamole:
            icon: {{HOMEPAGE_VAR_GUACAMOLE_ICON}} 
            href: {{HOMEPAGE_VAR_GUACAMOLE_URL}}
            sitemonitor: {{HOMEPAGE_VAR_GUACAMOLE_URL}}
    - Backup: 
        - Backrest:
            icon: {{HOMEPAGE_VAR_BACKREST_ICON}}
            href: {{HOMEPAGE_VAR_BACKREST_URL}}
            ping: {{HOMEPAGE_VAR_BACKREST_URL}}
        - remote-backups:
            icon: {{HOMEPAGE_VAR_REMOTEBACKUP_ICON}}
            href: {{HOMEPAGE_VAR_REMOTEBACKUP_URL}}
    - Media:
        - Jellyfin:
            icon: {{HOMEPAGE_VAR_JELLY_ICON}}
            href: {{HOMEPAGE_VAR_JELLY_URL}}
            ping: {{HOMEPAGE_VAR_JELLY_URL}}
            widget:
                type: jellyfin
                url: {{HOMEPAGE_VAR_JELLY_URL}} 
                key: {{HOMEPAGE_VAR_JELLY_KEY}}
                enableBlock: {{HOMEPAGE_VAR_JELLY_ENABLEBLOCK}}
                enableNowPlaying: {{HOMEPAGE_VAR_JELLY_NOWPLAY}}
        - Immich:
            icon: {{HOMEPAGE_VAR_IMMICH_ICON}} 
            href: {{HOMEPAGE_VAR_IMMICH_URL}}
            sitemonitor: {{HOMEPAGE_VAR_IMMICH_URL}}
            widget:
                type: immich
                url: {{HOMEPAGE_VAR_IMMICH_URL}} 
                key: {{HOMEPAGE_VAR_IMMICH_KEY}}
                version: {{HOMEPAGE_VAR_IMMICH_VERSION}}
                fields:  {{HOMEPAGE_VAR_IMMICH_FIELDS}}  
    - Local Apps: # remote
        - Actual:
            icon: {{HOMEPAGE_VAR_ACTUAL_ICON}}
            href: {{HOMEPAGE_VAR_ACTUAL_URL}}
        - SteamentSensei:
            icon: {{HOMEPAGE_VAR_SENSEI_ICON}}
            href: {{HOMEPAGE_VAR_SENSEI_URL}} 
            sitemonitor: {{HOMEPAGE_VAR_SENSEI_URL}}
        - Homeassistant:
            icon: {{HOMEPAGE_VAR_HA_ICON}}
            href: {{HOMEPAGE_VAR_HA_URL}}
            sitemonitor: {{HOMEPAGE_VAR_HA_URL}}
        - Sh:
            icon: {{HOMEPAGE_VAR_STASH_ICON}}
            href: {{HOMEPAGE_VAR_STASH_URL}}
            sitemonitor: {{HOMEPAGE_VAR_STASH_URL}}
            widget:
                type: stash
                url: {{HOMEPAGE_VAR_STASH_URL}}
                stashapikey: {{HOMEPAGE_VAR_STASH_API}}
        - Semaphore:
            icon: {{HOMEPAGE_VAR_SEMAPHORE_ICON}}
            href: {{HOMEPAGE_VAR_SEMAPHORE_URL}}
            sitemonitor: {{HOMEPAGE_VAR_SEMAPHORE_URL}}
        - aria2:
            icon: {{HOMEPAGE_VAR_ARIA_ICON}}
            href: {{HOMEPAGE_VAR_ARIA_URL}}
            sitemonitor: {{HOMEPAGE_VAR_ARIA_URL}}
        - nzbget:
            icon: {{HOMEPAGE_VAR_NZBGET_ICON}}
            href: {{HOMEPAGE_VAR_NZBGET_URL}}
            ping: {{HOMEPAGE_VAR_NZBGET_URL}}
- External:
    - Core: 
        - Komodo:
            icon: {{HOMEPAGE_VAR_KOMODO_ICON}} 
            href: {{HOMEPAGE_VAR_KOMODO_URL}}
            sitemonitor: {{HOMEPAGE_VAR_KOMODO_URL}}
            widget:
                type: komodo
                url:  {{HOMEPAGE_VAR_KOMODO_URL}}
                key: K-vtbPvxMmX1XWDnFN0QuTY2VVaaXNiHVWLilfv7IP
                #key: {{HOMEPAGE_VAR_KOMODO_KEY}}
                secret: S-MrzRNua1nyIKQNIJcpkOJCFqLx2oSJsM4g6pzVJz
                #secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
                showSummary: true # optional, default: false
                showStacks: true # optional, default: false
        - Dozzle:
            icon: {{HOMEPAGE_VAR_DOZZLE_ICON}}
            href: {{HOMEPAGE_VAR_DOZZLE_URL}}
#        - Container Updates:
#            icon: {{HOMEPAGE_VAR_KOMODO_ICON}}
#            server: my-docker
            #container: komodo-core-1 
#            widget:
#                type: customapi
#                url: {{HOMEPAGE_VAR_KOMODO_CONTAINER_UPDATE_URL}}
#                refreshInterval: 30000
#                display: block
#                mappings:
#                  - field: total
#                    label: Containers
#                    format: number
#                  - field: updates
#                    label: With Updates
#                    format: number
    - Identity: 
        - Authentik:
            icon: {{HOMEPAGE_VAR_AUTHENTIK_ICON}}
            href: {{HOMEPAGE_VAR_AUTHENTIK_URL}}
            sitemonitor: {{HOMEPAGE_VAR_AUTHENTIK_URL}}
            widget:
                type: authentik
                url: {{HOMEPAGE_VAR_AUTHENTIK_URL}}
                key: {{HOMEPAGE_VAR_AUTHENTIK_KEY}} 
    - Zero Trust: 
        - Pangolin:
            icon: {{HOMEPAGE_VAR_PANGOLIN_ICON}}
            href: {{HOMEPAGE_VAR_PANGOLIN_URL}}
            sitemonitor: {{HOMEPAGE_VAR_PANGOLIN_URL}}
        - Twingate:
            icon: {{HOMEPAGE_VAR_TWINGATE_ICON}}
            href: {{HOMEPAGE_VAR_TWINGATE_URL}}
    - Remote:
        - Guacamole:
            icon: {{HOMEPAGE_VAR_GUACAMOLE_ICON}} 
            href: {{HOMEPAGE_VAR_GUACAMOLEEXT_URL}}
            sitemonitor: {{HOMEPAGE_VAR_GUACAMOLEEXT_URL}}
        - Dumbterm:
            icon: {{HOMEPAGE_VAR_DUMBTERM_ICON}}
            href: {{HOMEPAGE_VAR_DUMBTERM_URL}}
            sitemonitor: {{HOMEPAGE_VAR_DUMBTERM_URL}}
        - Shellhub:
            icon: {{HOMEPAGE_VAR_SHELLHUB_ICON}}
            href: {{HOMEPAGE_VAR_SHELLHUB_URL}}
        - Termix:
            icon: {{HOMEPAGE_VAR_TERMIX_ICON}}
            href: {{HOMEPAGE_VAR_TERMIX_URL}}

    - Monitoring:
        - Uptime-Kuma:
            icon: {{HOMEPAGE_VAR_KUMA_ICON}}
            href: {{HOMEPAGE_VAR_KUMA_URL}}
        - Grafana on:
            icon: {{HOMEPAGE_VAR_GRAFANA_ICON}}
            href: {{HOMEPAGE_VAR_GRAFANAPANGOLIN_URL}}
        - Grafana:
            icon: {{HOMEPAGE_VAR_GRAFANA_ICON}}
            href: {{HOMEPAGE_VAR_GRAFANA_URL}}
        - Scrutiny:
            icon: {{HOMEPAGE_VAR_SCRUTINY_ICON}}
            href: {{HOMEPAGE_VAR_SCRUTINY_URL}}
        - Pulse:
            icon: {{HOMEPAGE_VAR_PULSEXT_ICON}}
            href: {{HOMEPAGE_VAR_PULSEXT_URL}}
        - Beszel:
            icon: {{HOMEPAGE_VAR_BESZEL_ICON}} 
            href: {{HOMEPAGE_VAR_BESZEL_URL}}
            sitemonitor: {{HOMEPAGE_VAR_BESZEL_URL}}
            widget:
                type: beszel
                #url: https://beszel.d3hl.cc
                url: http://10.10.10.9:8090
                username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
                password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}} 
                version: {{HOMEPAGE_VAR_BESZEL_VERSION}}
        - zabbix:
            icon: {{HOMEPAGE_VAR_ZABBIX_ICON}} 
            href: {{HOMEPAGE_VAR_ZABBIX_URL}}
            sitemonitor: {{HOMEPAGE_VAR_ZABBIX_URL}}
        - checkmk:
            icon: {{HOMEPAGE_VAR_CHECKMK_ICON}}
            href: {{HOMEPAGE_VAR_CHECKMK_URL}}
            sitemonitor: {{HOMEPAGE_VAR_CHECKMK_URL}}
        - Netbox Cloud:
            icon: {{HOMEPAGE_VAR_NETBOX_ICON}}
            href: {{HOMEPAGE_VAR_NETBOXCL_URL}}
        - Netbox Console:
            icon: {{HOMEPAGE_VAR_NETBOX_ICON}}
            href: {{HOMEPAGE_VAR_NETBOXCS_URL}}
        - Nautobox:
            icon: {{HOMEPAGE_VAR_NAUTOBOT_ICON}}
            href: {{HOMEPAGE_VAR_NAUTOBOT_URL}}
        - phpipam:
            icon: {{HOMEPAGE_VAR_PHPIPAM_ICON}}
            href: {{HOMEPAGE_VAR_PHPIPAM_URL}}
    - Apps: # Applications
        - Karakeep:
            icon: {{HOMEPAGE_VAR_KARAKEEP_ICON}}
            href: {{HOMEPAGE_VAR_KARAKEEP_URL}}
            sitemonitor: {{HOMEPAGE_VAR_KARAKEEP_URL}}
        - wallos:
            icon: {{HOMEPAGE_VAR_WALLOS_ICON}} 
            href: {{HOMEPAGE_VAR_WALLOS_URL}}
            sitemonitor: {{HOMEPAGE_VAR_WALLOS_URL}}
        - Omni-tools:
            icon: {{HOMEPAGE_VAR_OMNITOOLS_ICON}} 
            href: {{HOMEPAGE_VAR_OMNITOOLS_URL}}
            sitemonitor: {{HOMEPAGE_VAR_OMNITOOLS_URL}}
        - Selfhst-icons:
            icon: {{HOMEPAGE_VAR_SELFHST_ICON}} 
            href: {{HOMEPAGE_VAR_SELFHST_URL}}
- GL4:
    - PVE Dashboad:
        widget:
            type: iframe
            name: pveDashboard
            src: {{HOMEPAGE_VAR_PULSE_URL}}
            #classes: {{HOMEPAGE_VAR_PULSE_CLASSES}}
            allowfullscreen: {{HOMEPAGE_VAR_PULSE_ALLOWFULLSCREEN}}
            loadingStraegy: {{HOMEPAGE_VAR_PULSE_LOADING_STRATEGY}}
            allowScrolling: {{HOMEPAGE_VAR_PULSE_ALLOW_SCROLLING}}
            referrerPolicy: same-origin # optional, no default
            height: {{HOMEPAGE_VAR_PULSE_HEIGHT}}

### CORP TAB ###    
- WorkLeft:    
    - Applications:
        - PVECORP:
            icon: {{HOMEPAGE_VAR_PROXMOX_ICON}} 
            href: {{HOMEPAGE_VAR_PVECORP_URL}} 
        - Komodocorp:
            icon: {{HOMEPAGE_VAR_KOMODO_ICON}} 
            href: {{HOMEPAGE_VAR_KOMODOCORP_URL}} 
        - Fenrus:
            icon: {{HOMEPAGE_VAR_FENRUS_ICON}} 
            href: {{HOMEPAGE_VAR_FENRUS_URL}} 
    - Systems:
        - Wordpress:
            icon: wordpress
            href: https://ntn.com.sg/wp-login.php

### CLOUD TAB ###        
- WorkRight:    
    - Network:
        - Fortigate:
            icon: fortinet 
            href: http://fw.ntn.com.sg:7443 
        - FortiAnalyzer:
            icon: fortinet 
            href: http://faz.ntn.com.sg
        - FortiEMS:
            icon: fortinet
            href: http://ems.ntn.com.sg
        - Cisco:
            icon: cisco 
            href: http://10.203.1.254/webui 
        - Synology:
            icon: synology 
            href: http://10.203.1.111:5000 
        - Crestron:
            icon: https://static.wixstatic.com/media/007dac_d97541360d5849a492f61055994b510e~mv2.png/v1/fill/w_281,h_281,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/007dac_d97541360d5849a492f61055994b510e~mv2.png
            href: http://10.203.7.125
        - Ruckus:
            icon: rundeck 
            href: http://10.203.6.200
### CLOUD TAB ###        
- M365:
    - Intune:
        icon: /icons/microsoft-365.png 
        href: https://intune.microsoft.com
    - Entra:
        icon: /icons/microsoft-365.png
        href: https://entra.microsoft.com
    - Azure Portal:
        icon: /icons/azure.png
        href: https://portal.azure.com
    - AzureDevOps:
        icon: /icons/azure-devops.png 
        href: https://dev.azure.com/ntnsg/intune
