- Infra Core:
    - PVE:
        icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
        href: {{HOMEPAGE_VAR_PROXMOX_URL_PVE11}}
        sitemonitor: {{HOMEPAGE_VAR_PROXMOX_URL_PVE11}}
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PROXMOX_IP_PVE11}}
            username: {{HOMEPAGE_VAR_PROXMOX_USER}}
           # password: {{HOMEPAGE_VAR_PROXMOX_SECRET}}
            password: 8cc78ffc-dd21-438f-8787-e4ab2ca48a16 
            node: pve11
    -  Truenas:
        id: truenas 
        icon: {{HOMEPAGE_VAR_TRUENAS_ICON}}
        href: {{HOMEPAGE_VAR_TRUENAS_URL}}
        sitemonitor: {{HOMEPAGE_VAR_TRUENAS_URL}}
        widget:
            type: truenas
            url: {{HOMEPAGE_VAR_TRUENAS_URL}}
            key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
            enablePools: {{HOMEPAGE_VAR_TRUENAS_ENABLEDPOOL}}
            nasType: scale
    - Komodo:
        icon: {{HOMEPAGE_VAR_KOMODO_ICON}} 
        href: {{HOMEPAGE_VAR_KOMODO_URL}}
        sitemonitor: {{HOMEPAGE_VAR_KOMODO_URL}}
        widget:
            type: komodo
            url:  {{HOMEPAGE_VAR_KOMODO_API_URL}}
            key: {{HOMEPAGE_VAR_KOMODO_KEY}}
            secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
            showSummary: true # optional, default: false
            showStacks: true # optional, default: false
    - Homeassistant:
        icon: {{HOMEPAGE_VAR_HA_ICON}}
        href: {{HOMEPAGE_VAR_HA_URL}}
        sitemonitor: {{HOMEPAGE_VAR_HA_URL}}
- Domain:
    - GoDoxy:
        icon: {{HOMEPAGE_VAR_GODOXY_ICON}}
        href: {{HOMEPAGE_VAR_GODOXY_URL}} 
        ping: {{HOMEPAGE_VAR_GODOXY_URL}}
    - Technitium:
        icon: {{HOMEPAGE_VAR_DNS_ICON}}
        href: {{HOMEPAGE_VAR_DNS_URL}}
        ping: {{HOMEPAGE_VAR_DNS_URL}}
        widget:
            type: technitium
            url: {{HOMEPAGE_VAR_DNS_URL}}
            key: {{HOMEPAGE_VAR_DNS_KEY}}
            range: {{HOMEPAGE_VAR_DNS_RANGE}}
- Network:
    - NetAlertX:
        icon: {{HOMEPAGE_VAR_NETALERTX_ICON}}
        href: {{HOMEPAGE_VAR_NETALERTX_URL}}
        ping: {{HOMEPAGE_VAR_NETALERTX_URL}}
        widget:
            type: netalertx
            key: {{HOMEPAGE_VAR_NETALERTX_KEY}}
            url: {{HOMEPAGE_VAR_NETALERTX_URL}}
            fields: {{HOMEPAGE_VAR_NETALERTX_FIELDS}}
    - Tplink:
        icon: {{HOMEPAGE_VAR_TPLINK_ICON}} 
        href: {{HOMEPAGE_VAR_TPLINK_URL}}
        sitemonitor: {{HOMEPAGE_VAR_TPLINK_URL}}
    - Uptime-Kuma:
        icon: {{HOMEPAGE_VAR_KUMA_ICON}}
        href: {{HOMEPAGE_VAR_KUMA_URL}}
- Monitor:
    - Speedtest:
        icon: {{HOMEPAGE_VAR_SPEEDTEST_ICON}}
        href: {{HOMEPAGE_VAR_SPEEDTEST_URL}}
    - Wazuh:
        icon: {{HOMEPAGE_VAR_WAZUH_ICON}}
        href: {{HOMEPAGE_VAR_WAZUH_URL}}
        ping: {{HOMEPAGE_VAR_WAZUH_URL}}
    - Dozzle:
        icon: {{HOMEPAGE_VAR_DOZZLE_ICON}}
        href: {{HOMEPAGE_VAR_DOZZLE_URL}}
    - Apprise-API:
        icon: {{HOMEPAGE_VAR_APPRISE_ICON}}
        href: {{HOMEPAGE_VAR_APPRISE_URL}}
        sitemonitor: {{HOMEPAGE_VAR_APPRISE_URL}}
    - Healthcheck:
        icon: {{HOMEPAGE_VAR_HEALTHCHECKS_ICON}}
        href: {{HOMEPAGE_VAR_HEALTHCHECKS_URL}}
        sitemonitor: {{HOMEPAGE_VAR_HEALTHCHECKS_URL}}
    - Smokeping:
        icon: {{HOMEPAGE_VAR_SMOKEPING_ICON}}
        href: {{HOMEPAGE_VAR_SMOKEPING_URL}}
        sitemonitor: {{HOMEPAGE_VAR_SMOKEPING_URL}}
    - Guacamole:
        icon: {{HOMEPAGE_VAR_GUACAMOLE_ICON}} 
        href: {{HOMEPAGE_VAR_GUACAMOLE_URL}}
        sitemonitor: {{HOMEPAGE_VAR_GUACAMOLE_URL}}
- Backup: 
    - PBS: 
        icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
        href: {{HOMEPAGE_VAR_PBS_URL}}
        ping: {{HOMEPAGE_VAR_PBS_URL}} 
        widget:
            type: beszel
            url: http://10.10.10.9:8090
            username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
            password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}} 
            version: {{HOMEPAGE_VAR_BESZEL_VERSION}}
            systemId: {{HOMEPAGE_VAR_BESZEL_SYSTEMID_pbs}}
            fields: {{HOMEPAGE_VAR_BESZEL_FIELDS}}
    - Backrest:
        icon: {{HOMEPAGE_VAR_BACKREST_ICON}}
        href: {{HOMEPAGE_VAR_BACKREST_URL}}
        ping: {{HOMEPAGE_VAR_BACKREST_URL}}
    - remote-backups:
        icon: {{HOMEPAGE_VAR_REMOTEBACKUP_ICON}}
        href: {{HOMEPAGE_VAR_REMOTEBACKUP_URL}}
- Media:
    - Jellyfin:
        icon: {{HOMEPAGE_VAR_JELLY_ICON}}
        href: {{HOMEPAGE_VAR_JELLY_URL}}
        ping: {{HOMEPAGE_VAR_JELLY_URL}}
        widget:
            type: jellyfin
            url: {{HOMEPAGE_VAR_JELLY_URL}} 
            key: {{HOMEPAGE_VAR_JELLY_KEY}}
            enableBlock: {{HOMEPAGE_VAR_JELLY_ENABLEBLOCK}}
            enableNowPlaying: {{HOMEPAGE_VAR_JELLY_NOWPLAY}}
    - Immich:
        icon: {{HOMEPAGE_VAR_IMMICH_ICON}} 
        href: {{HOMEPAGE_VAR_IMMICH_URL}}
        sitemonitor: {{HOMEPAGE_VAR_IMMICH_URL}}
        widget:
            type: immich
            url: {{HOMEPAGE_VAR_IMMICH_URL}} 
            key: {{HOMEPAGE_VAR_IMMICH_KEY}}
            version: {{HOMEPAGE_VAR_IMMICH_VERSION}}
            fields:  {{HOMEPAGE_VAR_IMMICH_FIELDS}}  
- Access:
    - Guacamole:
        icon: {{HOMEPAGE_VAR_GUACAMOLE_ICON}} 
        href: {{HOMEPAGE_VAR_GUACAMOLEEXT_URL}}
        sitemonitor: {{HOMEPAGE_VAR_GUACAMOLEEXT_URL}}
    - Dumbterm:
        icon: {{HOMEPAGE_VAR_DUMBTERM_ICON}}
        href: {{HOMEPAGE_VAR_DUMBTERM_URL}}
        sitemonitor: {{HOMEPAGE_VAR_DUMBTERM_URL}}
    - Shellhub:
        icon: {{HOMEPAGE_VAR_SHELLHUB_ICON}}
        href: {{HOMEPAGE_VAR_SHELLHUB_URL}}
    - Termix:
        icon: {{HOMEPAGE_VAR_TERMIX_ICON}}
        href: {{HOMEPAGE_VAR_TERMIX_URL}}
- Troubleshoot: 
    - Dozzle:
        icon: {{HOMEPAGE_VAR_DOZZLE_ICON}}
        href: {{HOMEPAGE_VAR_DOZZLE_URL}}
- Identity: 
    - Authentik:
        icon: {{HOMEPAGE_VAR_AUTHENTIK_ICON}}
        href: {{HOMEPAGE_VAR_AUTHENTIK_URL}}
        sitemonitor: {{HOMEPAGE_VAR_AUTHENTIK_URL}}
        widget:
            type: authentik
            url: {{HOMEPAGE_VAR_AUTHENTIK_URL}}
            key: {{HOMEPAGE_VAR_AUTHENTIK_KEY}} 
    - Pangolin:
        icon: {{HOMEPAGE_VAR_PANGOLIN_ICON}}
        href: {{HOMEPAGE_VAR_PANGOLIN_URL}}
        sitemonitor: {{HOMEPAGE_VAR_PANGOLIN_URL}}
    - Twingate:
        icon: {{HOMEPAGE_VAR_TWINGATE_ICON}}
        href: {{HOMEPAGE_VAR_TWINGATE_URL}}