- Infra Core:
    - PVE:
        icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
        href: {{HOMEPAGE_VAR_PROXMOX_URL_PVE11}}
        sitemonitor: {{HOMEPAGE_VAR_PROXMOX_URL_PVE11}}
        widget:
            type: proxmox
            url: https://10.10.10.11:8006
            #username: {{HOMEPAGE_VAR_PROXMOX_USER}}
            username: homepage@pam!api
            #password: {{HOMEPAGE_VAR_PROXMOX_SECRET}}
            password: 9a14e6c8-ccb0-44f1-82ff-88ed1bc9df1c
            node: pve11
    -  Truenas:
        id: truenas 
        icon: {{HOMEPAGE_VAR_TRUENAS_ICON}}
        href: {{HOMEPAGE_VAR_TRUENAS_URL}}
        sitemonitor: {{HOMEPAGE_VAR_TRUENAS_URL}}
        widget:
            type: truenas
            url: {{HOMEPAGE_VAR_TRUENAS_URL}}
            key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
            enablePools: {{HOMEPAGE_VAR_TRUENAS_ENABLEDPOOL}}
            nasType: scale
    - Komodo:
        icon: {{HOMEPAGE_VAR_KOMODO_ICON}} 
        href: {{HOMEPAGE_VAR_KOMODO_URL}}
        sitemonitor: {{HOMEPAGE_VAR_KOMODO_URL}}
        widget:
            type: komodo
            url: {{HOMEPAGE_VAR_KOMODO_IPURL}}
            key: {{HOMEPAGE_VAR_KOMODO_KEY}}
            secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
            showSummary: true # optional, default: false
            showStacks: true # optional, default: false
########################################################################################################################################################################################################

########################################################################################################################################################################################################
### CORP TAB ###    
- Office Core:
    - PVECORP:
        icon: {{HOMEPAGE_VAR_PROXMOX_ICON}} 
        href: {{HOMEPAGE_VAR_PVECORP_URL}} 
    - Komodocorp:
        icon: {{HOMEPAGE_VAR_KOMODO_ICON}} 
        href: {{HOMEPAGE_VAR_KOMODOCORP_URL}} 
    - Fenrus:
        icon: {{HOMEPAGE_VAR_FENRUS_ICON}} 
        href: {{HOMEPAGE_VAR_FENRUS_URL}} 
- Corp Systems:
    - Wordpress:
        icon: wordpress
        href: https://ntn.com.sg/wp-login.php
########################################################################################################################################################################################################
### CLOUD TAB ###        
- Corp Network:
    - Fortigate:
        icon: fortinet 
        href: http://fw.ntn.com.sg:7443 
    - FortiAnalyzer:
        icon: fortinet 
        href: http://faz.ntn.com.sg
    - FortiEMS:
        icon: fortinet
        href: http://ems.ntn.com.sg
    - Cisco:
        icon: cisco 
        href: http://10.203.1.254/webui 
    - Synology:
        icon: synology 
        href: http://10.203.1.111:5000 
    - Crestron:
        icon: https://static.wixstatic.com/media/007dac_d97541360d5849a492f61055994b510e~mv2.png/v1/fill/w_281,h_281,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/007dac_d97541360d5849a492f61055994b510e~mv2.png
        href: http://10.203.7.125
    - Ruckus:
        icon: rundeck 
        href: http://10.203.6.200
########################################################################################################################################################################################################
### CLOUD TAB ###        
- Corp Cloud:
    - Intune:
        icon: /icons/microsoft-365.png 
        href: https://intune.microsoft.com
    - Entra:
        icon: /icons/microsoft-365.png
        href: https://entra.microsoft.com
    - Azure Portal:
        icon: /icons/azure.png
        href: https://portal.azure.com
    - AzureDevOps:
        icon: /icons/azure-devops.png 
        href: https://dev.azure.com/ntnsg/intune
    