---
- Internal:
    - Nas:
        -  Truenas: 
            icon: /icons/truenas-scale.png
            href: https://192.168.2.7
            ping: 192.168.2.7
            widget:
                type: truenas
                url: https://192.168.2.7
                key: 1-zM5Mm8l4VdRa4WNybTWjVdHVM89TR7fkGj40DkYEPgFdkt83DYBea95J3SHe3uCe
                enablePools: true
                nasType: scale
    - Pve: # proxmoxx
        - pve11:
            icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
            href: {{HOMEPAGE_VAR_PROXMOX_URL_PVE_1}}
            sitemonitor: {{HOMEPAGE_VAR_PROXMOX_URL_PVE_1}}
        - PBS: 
            icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
            href: {{HOMEPAGE_VAR_PBS_URL}}
            sitemonitor: {{HOMEPAGE_VAR_PBS_URL}} 
    - M0nit0ring:
        - NetAlertX:
            icon: {{HOMEPAGE_VAR_NETALERTX_ICON}}
            href: {{HOMEPAGE_VAR_NETALERTX_URL}}
            sitemonitor: {{HOMEPAGE_VAR_NETALERTX_URL}}
        - Smokeping:
            icon: {{HOMEPAGE_VAR_SMOKEPING_ICON}}
            href: {{HOMEPAGE_VAR_SMOKEPING_URL}}
            sitemonitor: {{HOMEPAGE_VAR_SMOKEPING_URL}}
        - Guacamole:
            icon: {{HOMEPAGE_VAR_GUACAMOLE_ICON}} 
            href: {{HOMEPAGE_VAR_GUACAMOLE_URL}}
            sitemonitor: {{HOMEPAGE_VAR_GUACAMOLE_URL}}
        - Battle of the badwidth:
            icon: {{HOMEPAGE_VAR_BOTB_ICON}}
            href: {{HOMEPAGE_VAR_BOTB_URL}}