- Infra Core:
    - PVE:
        icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
        href: {{HOMEPAGE_VAR_PROXMOX_URL_PVE11}}
        sitemonitor: {{HOMEPAGE_VAR_PROXMOX_URL_PVE11}}
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PROXMOX_IP_PVE_1}}
            username: {{HOMEPAGE_VAR_PROXMOX_USER}}
           # password: {{HOMEPAGE_VAR_PROXMOX_SECRET}}
            password: 8cc78ffc-dd21-438f-8787-e4ab2ca48a16 
            node: pve11
    -  Truenas:
        id: truenas 
        icon: {{HOMEPAGE_VAR_TRUENAS_ICON}}
        href: {{HOMEPAGE_VAR_TRUENAS_URL}}
        sitemonitor: {{HOMEPAGE_VAR_TRUENAS_URL}}
        widget:
            type: truenas
            url: {{HOMEPAGE_VAR_TRUENAS_URL}}
            key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
            enablePools: {{HOMEPAGE_VAR_TRUENAS_ENABLEDPOOL}}
            nasType: scale
    - Komodo:
        icon: {{HOMEPAGE_VAR_KOMODO_ICON}} 
        href: {{HOMEPAGE_VAR_KOMODO_URL}}
        sitemonitor: {{HOMEPAGE_VAR_KOMODO_URL}}
        widget:
            type: komodo
            url:  {{HOMEPAGE_VAR_KOMODO_API_URL}}
            key: {{HOMEPAGE_VAR_KOMODO_KEY}}
            secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
            showSummary: true # optional, default: false
            showStacks: true # optional, default: false
    - Homeassistant:
        icon: {{HOMEPAGE_VAR_HA_ICON}}
        href: {{HOMEPAGE_VAR_HA_URL}}
        sitemonitor: {{HOMEPAGE_VAR_HA_URL}}
- Domain:
    - GoDoxy:
        icon: {{HOMEPAGE_VAR_GODOXY_ICON}}
        href: {{HOMEPAGE_VAR_GODOXY_URL}} 
        ping: {{HOMEPAGE_VAR_GODOXY_URL}}
    - Technitium:
        icon: {{HOMEPAGE_VAR_DNS_ICON}}
        href: {{HOMEPAGE_VAR_DNS_URL}}
        ping: {{HOMEPAGE_VAR_DNS_URL}}
        widget:
            type: technitium
            url: {{HOMEPAGE_VAR_DNS_URL}}
            key: {{HOMEPAGE_VAR_DNS_KEY}}
            range: {{HOMEPAGE_VAR_DNS_RANGE}}
- Network:
    - NetAlertX:
        icon: {{HOMEPAGE_VAR_NETALERTX_ICON}}
        href: {{HOMEPAGE_VAR_NETALERTX_URL}}
        ping: {{HOMEPAGE_VAR_NETALERTX_URL}}
        widget:
            type: netalertx
            key: {{HOMEPAGE_VAR_NETALERTX_KEY}}
            url: {{HOMEPAGE_VAR_NETALERTX_URL}}
            fields: {{HOMEPAGE_VAR_NETALERTX_FIELDS}}
    - Tplink:
        icon: {{HOMEPAGE_VAR_TPLINK_ICON}} 
        href: {{HOMEPAGE_VAR_TPLINK_URL}}
        sitemonitor: {{HOMEPAGE_VAR_TPLINK_URL}}
    - Uptime-Kuma:
        icon: {{HOMEPAGE_VAR_KUMA_ICON}}
        href: {{HOMEPAGE_VAR_KUMA_URL}}