title: "{{HOMEPAGE_VAR_TITLE}}"
favicon: "{{HOMEPAGE_VAR_FAVICON}}"

headerStyle: {{HOMEPAGE_VAR_HEADER_STYLE}}
background:
    image: "{{HOMEPAGE_VAR_IMG_URL}}"
    blur: "{{HOMEPAGE_VAR_IMG_BLUR}"
    saturate: "{{HOMEPAGE_VAR_IMG_SATURATE}}"
    brightness: "{{HOMEPAGE_VAR_IMG_BRIGHTNESS}}"
    opacity: "{{HOMEPAGE_VAR_IMG_OPACITY}}"
theme: dark 
color: zinc
statusStyle: "dot"
hideErrors: false
disableCollapse: true

# Layout Configuration
layout:
  # HOME Tab Items
  Infra:
      style: column
      tab: HOME
      icon: mdi-file-multiple
  Domain:
      style: column
      tab: HOME
      icon: mdi-multimedia