---
title: "{{HOMEPAGE_VAR_TITLE}}"
favicon: "{{HOMEPAGE_VAR_FAVICON}}"

headerStyle: {{HOMEPAGE_VAR_HEADER_STYLE}}
background:
  image: "{{HOMEPAGE_VAR_IMG_URL}}"
  blur: "{{HOMEPAGE_VAR_IMG_BLUR}"
  saturate: "{{HOMEPAGE_VAR_IMG_SATURATE}}"
  brightness: "{{HOMEPAGE_VAR_IMG_BRIGHTNESS}}"
  opacity: "{{HOMEPAGE_VAR_IMG_OPACITY}}"
theme: dark 
color: zinc
useEqualHeights: {{HOMEPAGE_VAR_USE_EQUAL_HEIGHTS}}
statusStyle: "dot"
showStats: {{HOMEPAGE_VAR_SHOW_STATS}}
hideErrors: false
disableCollapse: true

layout:
  Infra:
    tab: Homelab
    style: column
  Domain:
    tab: Homelab
    style: column
  Network:
    tab: Homelab
    style: column
  Monitor:
    tab: Homelab
    style: column
  Backup:
    tab: Homelab
    style: column
  Media:
    tab: Homelab
    style: column
  Access:
    tab: Homelab
    style: column
  Troubleshoot:
    tab: Homelab
    style: column
  Identity:
    tab: Homelab
    style: column

  M365:
    tab: Cloud
    style: row
    columns: 4
    Other Cloud:
      tab: Cloud
      style: column
      columns: 4
  WorkLeft:
    tab: Corp
    style: column
    columns: 1
    header: False
  WorkRight:
    tab: Corp
    style: column
    columns: 1
    header: False

  GL4:
    tab: Monitoring
    style: row
    colums: 4