title: "{{HOMEPAGE_VAR_TITLE}}"
favicon: "{{HOMEPAGE_VAR_FAVICON}}"

headerStyle: {{HOMEPAGE_VAR_HEADER_STYLE}}
background:
    image: "{{HOMEPAGE_VAR_IMG_URL}}"
    blur: "{{HOMEPAGE_VAR_IMG_BLUR}"
    saturate: "{{HOMEPAGE_VAR_IMG_SATURATE}}"
    brightness: "{{HOMEPAGE_VAR_IMG_BRIGHTNESS}}"
    opacity: "{{HOMEPAGE_VAR_IMG_OPACITY}}"
theme: dark 
color: zinc
statusStyle: "dot"
hideErrors: false
disableCollapse: true

# Layout Configuration
layout:
  # HOME Tab Items
  Infra Core:
      style: column
      tab: HOME
      icon: mdi-file-multiple
  Domain:
      style: column
      tab: HOME
      icon: mdi-multimedia
  Network:
      tab: Home
      style: column
  Monitor:
      tab: Home
      style: column
  Backup:
      tab: Home
      style: column
  Media:
      tab: Home
      style: column
  Access:
      tab: Home
      style: column
  Troubleshoot:
      tab: Home
      style: column
  Identity:
      tab: Home
      style: column
  Appplications:
      tab: Home
      style: column
  Tools:
      tab: Home
      style: column
  Extras:
      tab: Home
      style: column
  Office Core:
      tab: Corp
      style: column
  Corp Systems:
      tab: Corp
      style: column
  Corp Network:
      tab: Corp
      style: column
  Corp Cloud:
      tab: Corp
      style: column
    