---
title: d3 Homelab

backgorund:
#  image: /images/111rs.jpeg
  image: {{HOMEPAGE_VAR_IMG_URL}}

target: _self
headerStyle: boxedWidgets
fullWidth: true
showStats: true
hideErrors: true
layout:

  Internal:
    tab: Homelab
    style: column
    columns: 1 
    header: true
    Nas:
      style: row
      columns: 1 
      header: false
    Pve:
      style: row
      columns: 4 
      header: false
    M0nit0ring:
      style: row
      columns: 3 
      header: true
      useEqualHeights: true