title: "{{HOMEPAGE_VAR_TITLE}}"
favicon: "{{HOMEPAGE_VAR_FAVICON}}"

headerStyle: {{HOMEPAGE_VAR_HEADER_STYLE}}
background:
    image: "{{HOMEPAGE_VAR_IMG_URL}}"
    blur: "{{HOMEPAGE_VAR_IMG_BLUR}"
    saturate: "{{HOMEPAGE_VAR_IMG_SATURATE}}"
    brightness: "{{HOMEPAGE_VAR_IMG_BRIGHTNESS}}"
    opacity: "{{HOMEPAGE_VAR_IMG_OPACITY}}"
theme: dark 
color: zinc
useEqualHeights: {{HOMEPAGE_VAR_USE_EQUAL_HEIGHTS}}
statusStyle: "dot"
showStats: {{HOMEPAGE_VAR_SHOW_STATS}}
hideErrors: false
disableCollapse: true

layout:
    Infra:
        tab: Home
        style: column
    Domain:
        tab: Home
        style: column
    Network:
        tab: Home
        style: column
    Monitor:
        tab: Home
        style: column
    Backup:
        tab: Home
        style: column
    Media:
        tab: Home
        style: column
    Access:
        tab: Home
        style: column
    Troubleshoot:
        tab: Home
        style: column
    Identity:
        tab: Home
        style: column
 # M365:
  #    tab: Cloud
   #   style: row
    #  columns: 4
  #Other Cloud:
    #  tab: Cloud
   #   style: column
     # columns: 4
  #WorkLeft:
      #tab: Corp
      #style: column
      #columns: 1
      #header: False


#  GL4:
 #     tab: Monitoring
  #    style: row
   #   colums: 4