---
- logo:
    icon: /icons/d3logo.svg
#- openmeteo:
#    label: Singapore
#    latitude: 1.27
#    longitude: 103.8374
#    timezone: Asia/Singapore
#    cache: 5
#    units: metric
#- search:
#    provider: duckduckgo
#    target: _blank

- glances:
    url: {{HOMEPAGE_VAR_GL11_URL}}
    version: {{HOMEPAGE_VAR_GL11_VERSION}} 
    cpu: {{HOMEPAGE_VAR_GL11_CPU}} # optional, enabled by default, disable by setting to false
    mem: {{HOMEPAGE_VAR_GL11_MEM}} # optional, enabled by default, disable by setting to false
    cputemp: {{HOMEPAGE_VAR_GL11_CPUTEMP}} # disabled by default
    uptime: {{HOMEPAGE_VAR_GL11_UPTIME}} # disabled by default
    label: {{HOMEPAGE_VAR_GL11_LABEL}} # optional
- glances:
    url: {{HOMEPAGE_VAR_GL12_URL}}
    version: {{HOMEPAGE_VAR_GL12_VERSION}} 
    cpu: {{HOMEPAGE_VAR_GL12_CPU}} # optional, enabled by default, disable by setting to false
    mem: {{HOMEPAGE_VAR_GL12_MEM}} # optional, enabled by default, disable by setting to false
    cputemp: {{HOMEPAGE_VAR_GL12_CPUTEMP}} # disabled by default
    uptime: {{HOMEPAGE_VAR_GL12_UPTIME}} # disabled by default
    label: {{HOMEPAGE_VAR_GL12_LABEL}} # optional
- glances:
    url: {{HOMEPAGE_VAR_GL13_URL}}
    version: {{HOMEPAGE_VAR_GL13_VERSION}} 
    cpu: {{HOMEPAGE_VAR_GL13_CPU}} # optional, enabled by default, disable by setting to false
    mem: {{HOMEPAGE_VAR_GL13_MEM}} # optional, enabled by default, disable by setting to false
    cputemp: {{HOMEPAGE_VAR_GL13_CPUTEMP}} # disabled by default
    uptime: {{HOMEPAGE_VAR_GL13_UPTIME}} # disabled by default
    label: {{HOMEPAGE_VAR_GL13_LABEL}} # optional
