services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS} # optional, comma separated list of allowed hosts (e.g. "localhost, 
      PGID: 1000 # optional, your group id
      PUID: 1000 # optional, your user id
#      HOMEPAGE_FILE_SETTINGS: ${HOMEPAGE_FILE_SETTINGS}
#      HOMEPAGE_FILE_SERVICES: ${HOMEPAGE_FILE_SERVICES}
#      HOMEPAGE_FILE_WIDGETS: ${HOMEPAGE_FILE_WIDGETS}
#      HOMEPAGE_FILE_BOOKMARKS: ${HOMEPAGE_FILE_BOOKMARKS}
      HOMEPAGE_DATA_DIR: ${HOMEPAGE_DATA_DIR} # optional, path to your local config directory
      HOMEPAGE_ICON_DIR: ${HOMEPAGE_ICON_DIR} # optional, path to your local data directory
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - $(HOMEPAGE_DATA_DIR):/app/config # Make sure your local config directory exists
      - ${HOMEPAGE_ICON_DIR}:/app/public/icons # Make sure your local data directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped