DNS_SERVER_DOMAIN=dns.d3hl.site
DNS_SERVER_ADMIN_PASSWORD=op://d3HL/Technitium-dns/DNS_SERVER_ADMIN_PASSWORD
DNS_SERVER_PREFER_IPV6=false
DNS_SERVER_WEB_SERVICE_HTTP_PORT=5380
DNS_SERVER_WEB_SERVICE_HTTPS_PORT=53443


DNS_SERVER_FORWARDERS=1.1.1.1
DNS_SERVER_LOG_USING_LOCAL_TIME=true
DNS_SERVER_LOG_FOLDER_PATH=/var/log/technitium/dns
DNS_SERVER_WEB_SERVICE_USE_SELF_SIGNED_CERT=true
DNS_SERVER_WEB_SERVICE_TLS_CERTIFICATE_PATH="op://d3HL/Technitium-dns/DNS_SERVER_WEB_SERVICE_TLS_CERTIFICATE_PATH"
DNS_SERVER_WEB_SERVICE_TLS_CERTIFICATE_PASSWORD="op://d3HL/Technitium-dns/DNS_SERVER_WEB_SERVICE_TLS_CERTIFICATE_PASSWORD"
MYSQL_ROOT_PASSWORD=op://d3HL/Technitium-dns/MYSQL_ROOT_PASSWORD
MYSQL_USER=op://d3HL/Technitium-dns/MYSQL_USER
MYSQL_PASSWORD="op://d3HL/Technitium-dns/ MYSQL_PASSWORD"
CDATA=op://d3HL/Technitium-dns/cDATA

