name: bento
services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:latest
    container_name: bentopdf
    restart: unless-stopped
    ports:
      - '8003:8080'
    environment:
      - DISABLE_IPV6=true 
      - VITE_BRAND_NAME="Local PDF by Bento"
      - VITE_BRAND_LOGO="images/d3logo.png"
      - VITE_FOOTER_TEXT="© 2026 Internal use only."
