services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_UID=1001
      - PLEX_GID=1001
      - TZ=Asia/Singaore
      - PLEX_CLAIM=claim-GBp3xUsDNij9uvPPSN17
      - ADVERTISE_IP=http://10.10.10.38:32400/
    volumes:
      - /mnt/cFS/appdata/plex/database:/config
      - /mnt/cFS/appdata/plex/transcode/temp>:/transcode
      - /mnt/zApps/appdata/movies:/data