services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - PLEX_UID=1001
      - PLEX_GID=1001
      - TZ=Asia/Singaore
     # - PLEX_CLAIM=<claimToken>
    network_mode: host
    volumes:
      - /mnt/cFS/appdata/plex/database:/config
      - /mnt/cFS/appdata/plex/transcode/temp>:/transcode
      - /mnt/zApps/appdata/movies:/data