services:
  nexterm:
    environment:
      ENCRYPTION_KEY: "aba3aa8e29b9904d5d8d8515230b664c053415c54be20ad13be99af0057dfa23a"
    ports:
      - "6989:6989"
    restart: always
    volumes:
      - nexterm:/app/data
    image: germannewsmaker/nexterm:1.0.3-OPEN-PREVIEW
volumes:
  nexterm: