[[resource_sync]]
name = "sync"
[resource_sync.config]
repo = "d3adc3iii/dIIIhl"
git_account = "d3adc3iii"
resource_path = ["/komodo/resources/main.toml"]
managed = true
delete = true
include_variables = true
include_user_groups = true