[[server]]
name = "komodo-2"
[server.config]
address = "https://192.168.2.32:8120"
enabled = true

##

[[server]]
name = "server-bkxal"
[server.config]
address = "https://periphery:8120"
enabled = true

##

[[stack]]
name = "homepage"
[stack.config]
server = "server-bkxal"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "server11/homepage"

##

[[stack]]
name = "immich"
[stack.config]
server = "server-bkxal"
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "/etc/komodo/stacks/immich/server11/immich"

##

[[stack]]
name = "karakeep"
[stack.config]
server = "server-bkxal"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "server11/karakeep-app"
environment = """
KARAKEEP_VERSION=release
NEXTAUTH_SECRET=[[KARA_NEXTAUTH_SECRET]]
MEILI_MASTER_KEY=[[KARA_MEILI_MASTER_KEY]]
NEXTAUTH_URL=http://192.168.2.31:3333
OPENAI_API_KEY=[[OPENAI_API_KEY]]
DATA_DIR=/mnt/zApps/karakeep/data
"""

##
[[stack]]
name = "dumbterm"
[stack.config]
server = "komodo-2" 
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "/etc/komodo/stacks/dumbterm/server12/dumbterm"
environment = """
  DUMBTERM_CONFIG="/etc/komodo/stacks/dumbterm/app-data/dumbterm/config"
  DUMBTERM_DATA_DIR="/etc/komodo/stacks/dumbterm/app-data/dumbterm/data"
  DUMBTERM_TZ="Asia/Singapore"
  DUMBTERM_PIN=1111
  DUMBTERM_PORT=3002
  DUMBTERM_BASE_URL=https://localhost:3002
"""

##
[[stack]]
name = "semaphore"
[stack.config]
server = "komodo-2" 
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "/etc/komodo/stacks/semahore/server12/semaphore"
environment = """
"""
##

[[deployment]]
name = "twingate"
[deployment.config]
server = "komodo-2"
image.type = "Image"
image.params.image = "twingate/connector:latest"
poll_for_updates = true
auto_update = true
restart = "unless-stopped"
environment = """
  TWINGATE_NETWORK=d3net
  TWINGATE_ACCESS_TOKEN=eyJhbGciOiJFUzI1NiIsImtpZCI6Inp3dkU1dHpJZzV4X2pSVEU4RTFWQll6MW0tX2g1dXlMZlhTV1VSS1BEVE0iLCJ0eXAiOiJEQVQifQ.eyJudCI6IkFOIiwiYWlkIjoiNTExMjE5IiwiZGlkIjoiMjE5MTEwMCIsImp0aSI6ImIxZjU3N2FkLTZmNDItNDYyYS05ZGIzLTY1NTE5ZmQyMTJlNCIsImlzcyI6InR3aW5nYXRlIiwiYXVkIjoiZDNuZXQiLCJleHAiOjE3NDYxNDQ5MDAsImlhdCI6MTc0NjE0MTMwMCwidmVyIjoiNCIsInRpZCI6IjEwMzU2NCIsInJudyI6MTc0NjE0MTU3OCwicm5ldGlkIjoiMTM1OTMxIn0.OxT4qXnqonLPGb1GwJTRcYoSwZG16x2JGA_Xu2pOo0dZH3jpqfd1SkjWy8JjcVePboTum2e0WEdNu4SFcJUy_A
  TWINGATE_REFRESH_TOKEN=mrNJNc7hirY3gO3-q9l6dnN_YjYl-8q79XRXg1ffZstYm8EYyH6xNXMIVviMaQ-2-GAa4wuSMv1J5ebEf9KvzIK94jmq7j9QGPH2Tr7ZnjlYADuKrEpKUkrmnbrROkgQy6nzWg
  TWINGATE_LOG_ANALYTICS=v2
"""

##

[[repo]]
name = "diiihl"
[repo.config]
server = "server-bkxal"
builder = "local"
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "server-bkxal"

##

[[resource_sync]]
name = "sync"
[resource_sync.config]
repo = "d3adc3iii/dIIIhl"
git_account = "d3adc3iii"
resource_path = ["komodo/resources/main.toml"]
managed = true
delete = true
include_variables = true
include_user_groups = true

##

[[variable]]
name = "KARA_NEXTAUTH_SECRET"
value = "4obmXxlcc8M7RIi95R4gGcqvH2mD29LLLx4C+sXAd7rLvNpM"
is_secret = true

##

[[variable]]
name = "KARA_MEILI_MASTER_KEY"
value = "MwldJwDmieQWtyMZTTVi2yb2T0r2ZHeCNrAdgKeG1vTwpLWy"
is_secret = true

##

[[variable]]
name = "OPENAI_API_KEY"
value = "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"
is_secret = true