[[resource_sync]]
name = "sync"
tags = ["immich", "karakeep"]
[resource_sync.config]
repo = "d3adc3iii/dIIIhl"
git_account = "d3adc3iii"
resource_path = ["komodo/resources/main.toml"]
managed = true
match_tags = ["immich", "karakeep"]
include_variables = true