[[server]]
name = "komodo-2"
[server.config]
address = "https://192.168.2.32:8120"
enabled = true

##

[[server]]
name = "komodo-3"
[server.config]
address = "https://192.168.2.33:8120"
enabled = true

##

[[server]]
name = "server-bkxal"
[server.config]
address = "https://periphery:8120"
enabled = true

##

[[stack]]
name = "authentik"
tags = ["external", "critical"]
[stack.config]
server = "server-bkxal"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "server11/authentik"
environment = """
AUTHENTIK_SECRET_KEY= [[AUTHENTIK_SECRET_KEY]]
PG_PASS= [[PG_PASS]]

"""

##

[[stack]]
name = "battle-of-the-bandwidth"
tags = [
  "internal",
  "testing",
  "monitoring"
]
[stack.config]
server = "komodo-2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "/etc/komodo/stacks/battle-of-the-bandwidth/server12/battle-of-the-bandwidth"

##

[[stack]]
name = "corecontrol"
tags = ["internal", "testing"]
[stack.config]
server = "komodo-3"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "server13/corecontrol"
environment = """
JWT_SECRET=[[CORECONTROL_JWT_SECRET]]
POSTGRES_DATA=/mnt/zApps/corecontrol/data
"""

##

[[stack]]
name = "dumbterm"
tags = ["external", "production"]
[stack.config]
server = "komodo-2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "/etc/komodo/stacks/dumbterm/server12/dumbterm"
environment = """
  DUMBTERM_CONFIG="/mnt/zApps/dumbterm/config"
  DUMBTERM_DATA_DIR="/mnt/zApps/dumbterm/data"
  DUMBTERM_TZ="Asia/Singapore"
  DUMBTERM_PIN=1111
  DUMBTERM_PORT=3002
  DUMBTERM_BASE_URL=http://dumbterm.d3adc3ii.cc:3002
"""

##

[[stack]]
name = "homepage"
tags = ["external", "production"]
[stack.config]
server = "server-bkxal"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "server11/homepage"
environment = """
DATA_DIR= /etc/komodo/repos/diiihl/server11/homepage
ALLOWED_HOSTS= homepage.d3adc3ii.cc,192.168.2.31:3000
"""

##

[[stack]]
name = "immich"
tags = ["internal", "production"]
[stack.config]
server = "server-bkxal"
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "/etc/komodo/stacks/immich/server11/immich"

##

[[stack]]
name = "karakeep"
tags = ["external", "production"]
[stack.config]
server = "server-bkxal"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "server11/karakeep-app"
environment = """
KARAKEEP_VERSION=release
NEXTAUTH_SECRET=[[KARA_NEXTAUTH_SECRET]]
MEILI_MASTER_KEY=[[KARA_MEILI_MASTER_KEY]]
NEXTAUTH_URL=http://192.168.2.31:3333
OPENAI_API_KEY=[[OPENAI_API_KEY]]
DATA_DIR=/mnt/zApps/karakeep/data
"""

##

[[stack]]
name = "nzbget"
[stack.config]
server = "komodo-2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "server12/nzbget"
environment = """
NZBGET_USER= [[NZBGET_USER]]
NZBGET_PASS= [[NZBGET_PASS]]
NZBGET_CONFIG= /mnt/zApps/nzbget/config
NZBGET_DL= /mnt/zApps/nzbget/download
"""

##

[[stack]]
name = "portnote"
tags = [
  "internal",
  "testing",
  "monitoring"
]
[stack.config]
server = "komodo-3"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "server13/Portnote"
environment = """
JWT_SECRET=[[PORTNOTE_JWT_SECRET]]
USER_SECRET=[[PORTNOTE_USER_SECRET]]
LOGIN_USERNAME=d3
LOGIN_PASSWORD=[[PORTNOTE_LOGIN_PASSWORD]]
DATABASE_URL="postgresql://postgres:postgres@db:5432/postgres"
POSTGRES_DATA=/mnt/zApps/portnote/data
"""

##

[[stack]]
name = "prom-ga-alloy"
[stack.config]
server = "komodo-2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
run_directory = "server12/prom-gra-alloy"
environment = """
LOKI_CONFIG_FILE=/etc/komodo/stacks/prom-gra-alloy/server12/prom-gra-alloy/config/loki-config.yaml
ALLOY_CONFIG_FILE=/etc/komodo/stacks/prom-gra-alloy/server12/prom-gra-alloy/config/config.alloy
"""

##

[[deployment]]
name = "alloy"
[deployment.config]
server = "komodo-2"
image.type = "Image"
image.params.image = "grafana/alloy:latest"
poll_for_updates = true
auto_update = true
network = "bridge"
restart = "unless-stopped"
command = "run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data etc/alloy/config.alloy"
ports = """
 12345:12345
"""
volumes = """
/etc/komodo/repos/diiihl-k2/server12/alloy/config/config.alloy:/etc/alloy/config.alloy
"""
environment = """

"""

##

[[deployment]]
name = "beszel-k11"
tags = ["internal", "monitoring"]
[deployment.config]
server = "server-bkxal"
image.type = "Image"
image.params.image = "henrygd/beszel-agent"
poll_for_updates = true
auto_update = true
restart = "unless-stopped"
volumes = """
/var/run/docker.sock:/var/run/docker.sock:ro
"""
environment = """
LISTEN=45876
KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJq8OcGRupFySjJHa5aIjeWFHd17+Lfwn+TVfwU6cTY/"
  # VARIABLE = value
"""

##

[[deployment]]
name = "beszel-k12"
tags = ["internal", "monitoring"]
[deployment.config]
server = "komodo-2"
image.type = "Image"
image.params.image = "henrygd/beszel-agent"
poll_for_updates = true
auto_update = true
restart = "unless-stopped"
volumes = """
/var/run/docker.sock:/var/run/docker.sock:ro
"""
environment = """
LISTEN=45876
KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJq8OcGRupFySjJHa5aIjeWFHd17+Lfwn+TVfwU6cTY/"
"""

##

[[deployment]]
name = "nessus"
tags = ["internal", "testing"]
[deployment.config]
server = "komodo-2"
image.type = "Image"
image.params.image = "tenable/nessus:latest-ubuntu"

##

[[deployment]]
name = "newt1"
tags = ["external", "production"]
[deployment.config]
server = "server-bkxal"
image.type = "Image"
image.params.image = "fosrl/newt"
poll_for_updates = true
auto_update = true
restart = "unless-stopped"
environment = """
  PANGOLIN_ENDPOINT=https://pangolin.d3adc3ii.cc
  NEWT_ID=[[NEWT_ID1]]
  NEWT_SECRET=[[NEWT_SECRET1]]
"""

##

[[deployment]]
name = "newt2"
tags = ["external", "production"]
[deployment.config]
server = "komodo-2"
image.type = "Image"
image.params.image = "fosrl/newt"
poll_for_updates = true
auto_update = true
restart = "unless-stopped"
environment = """
  PANGOLIN_ENDPOINT=https://pangolin.d3adc3ii.cc
  NEWT_ID=[[NEWT_ID2]]
  NEWT_SECRET=[[NEWT_SECRET2]]
"""

##

[[deployment]]
name = "omni-tools"
tags = ["external", "testing"]
[deployment.config]
server = "komodo-2"
image.type = "Image"
image.params.image = "iib0011/omni-tools:latest"
poll_for_updates = true
auto_update = true
network = "bridge"
restart = "unless-stopped"
ports = """
8281:80
"""

##

[[deployment]]
name = "statementsensei"
tags = ["internal", "testing"]
[deployment.config]
server = "komodo-2"
image.type = "Image"
image.params.image = "benjaminawd/statementsensei:latest"
poll_for_updates = true
auto_update = true
network = "bridge"
ports = """
8501:8501
"""
environment = """
  PDF_PASSWORD= [[PDF_PASSWORD]]
"""

##

[[deployment]]
name = "twingate"
tags = ["external", "production"]
[deployment.config]
server = "komodo-2"
image.type = "Image"
image.params.image = "twingate/connector:latest"
poll_for_updates = true
auto_update = true
restart = "unless-stopped"
environment = """
  TWINGATE_NETWORK=d3net
  TWINGATE_ACCESS_TOKEN=eyJhbGciOiJFUzI1NiIsImtpZCI6Inp3dkU1dHpJZzV4X2pSVEU4RTFWQll6MW0tX2g1dXlMZlhTV1VSS1BEVE0iLCJ0eXAiOiJEQVQifQ.eyJudCI6IkFOIiwiYWlkIjoiNTExMjE5IiwiZGlkIjoiMjE5MTEwMCIsImp0aSI6ImIxZjU3N2FkLTZmNDItNDYyYS05ZGIzLTY1NTE5ZmQyMTJlNCIsImlzcyI6InR3aW5nYXRlIiwiYXVkIjoiZDNuZXQiLCJleHAiOjE3NDYxNDQ5MDAsImlhdCI6MTc0NjE0MTMwMCwidmVyIjoiNCIsInRpZCI6IjEwMzU2NCIsInJudyI6MTc0NjE0MTU3OCwicm5ldGlkIjoiMTM1OTMxIn0.OxT4qXnqonLPGb1GwJTRcYoSwZG16x2JGA_Xu2pOo0dZH3jpqfd1SkjWy8JjcVePboTum2e0WEdNu4SFcJUy_A
  TWINGATE_REFRESH_TOKEN=mrNJNc7hirY3gO3-q9l6dnN_YjYl-8q79XRXg1ffZstYm8EYyH6xNXMIVviMaQ-2-GAa4wuSMv1J5ebEf9KvzIK94jmq7j9QGPH2Tr7ZnjlYADuKrEpKUkrmnbrROkgQy6nzWg
  TWINGATE_LOG_ANALYTICS=v2
"""

##

[[repo]]
name = "diiihl"
[repo.config]
server = "server-bkxal"
builder = "local"
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"

##

[[repo]]
name = "diiihl-k2"
[repo.config]
server = "komodo-2"
builder = "local"
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"

##

[[alerter]]
name = "test-alert"
[alerter.config]


##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "server-bkxal"

##

[[resource_sync]]
name = "sync"
[resource_sync.config]
repo = "d3adc3iii/dIIIhl"
git_account = "d3adc3iii"
resource_path = ["komodo/resources/main.toml"]
managed = true
delete = true
include_variables = true
include_user_groups = true

##

[[variable]]
name = "KARA_NEXTAUTH_SECRET"
value = "4obmXxlcc8M7RIi95R4gGcqvH2mD29LLLx4C+sXAd7rLvNpM"
is_secret = true

##

[[variable]]
name = "KARA_MEILI_MASTER_KEY"
value = "MwldJwDmieQWtyMZTTVi2yb2T0r2ZHeCNrAdgKeG1vTwpLWy"
is_secret = true

##

[[variable]]
name = "OPENAI_API_KEY"
value = "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"
is_secret = true

##

[[variable]]
name = "AUTHENTIK_SECRET_KEY"
value = "_7WB2IB9GR612BYM9A9VTRS4OHFNOA0DV"
is_secret = true

##

[[variable]]
name = "PG_PASS"
value = "RAMKPLQF6F5FGKBZ6IH4UP4UPFPO6W2M"
is_secret = true

##

[[variable]]
name = "NEWT_ID2"
description = "for newt 2"
value = "n04e204hc6rp5yk"
is_secret = true

##

[[variable]]
name = "NEWT_SECRET2"
value = "fynufrzgj21byeusity9xojmox07l1fr6yoe2fpsg0dg7kwd"
is_secret = true

##

[[variable]]
name = "NEWT_ID1"
value = "sc90bcxcbkg0smq"
is_secret = true

##

[[variable]]
name = "NEWT_SECRET1"
value = "v5mkixs9kuz5oydxut39c17tody3ksttjk5b9utld02b8lwd"
is_secret = true

##

[[variable]]
name = "PORTNOTE_JWT_SECRET"
value = "XxockagcY8ApPXCUh6Ujo1Qu4sdrXwcb"
is_secret = true

##

[[variable]]
name = "PORTNOTE_USER_SECRET"
value = "NBcMXXPJrGb7OPIzrRGgbCgvG5Gja2kK"
is_secret = true

##

[[variable]]
name = "PORTNOTE_LOGIN_PASSWORD"
value = "jp2Pt7CG0AX5Y3Q0P3Inx8ESxyYUtVT2"
is_secret = true

##

[[variable]]
name = "CORECONTROL_JWT_SECRET"
value = "^yv&5>qxi0#?C#^zqIqz(#81xBvY8?LEQkxj?U:Sd,uk^,K&>B=^zts*xT|~O|p"
is_secret = true

##

[[variable]]
name = "NZBGET_PASS"
value = "1VSHxgJx1F6FeDmizVLSFh3rtX1v1WBW"
is_secret = true

##

[[variable]]
name = "NZBGET_USER"
value = "d3"
is_secret = true

##

[[variable]]
name = "PDF_PASSWORD"
value = "Abcd1234"
is_secret = true