[[server]]
name = "komodo2"
[server.config]
address = "https://192.168.2.25:8120"
enabled = true

##

[[server]]
name = "server-76ich"
[server.config]
address = "https://periphery:8120"
enabled = true

##

[[stack]]
name = "immich-app"
tags = ["immich"]
[stack.config]
server = "server-76ich"
run_build = true
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
reclone = true
webhook_force_deploy = true
run_directory = "server13/immich-app"
additional_env_files = [".env"]
environment = """
  DB_PASSWORD=[[IMMICH_DB_PASSWORD]]
  DB_USERNAME=postgres
  DB_DATABASE_NAME=immich

"""

##

[[stack]]
name = "jhjlk"
[stack.config]


##

[[stack]]
name = "kara_stack"
tags = ["karakeep"]
[stack.config]
server = "server-76ich"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
reclone = true
run_directory = "karakeep-app"
environment = """
KARAKEEP_VERSION=release
NEXTAUTH_SECRET=4obmXxlcc8M7RIi95R4gGcqvH2mD29LLLx4C+sXAd7rLvNpM
MEILI_MASTER_KEY=MwldJwDmieQWtyMZTTVi2yb2T0r2ZHeCNrAdgKeG1vTwpLWy
NEXTAUTH_URL=http://localhost:3000
OPENAI_API_KEY=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

"""

##

[[repo]]
name = "diiihl"
[repo.config]
server = "server-76ich"
builder = "local"
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"

##

[[procedure]]
name = "l"

##

[[action]]
name = "action"
[action.config]
file_contents = """
// Run actions using the pre initialized 'komodo' client.
const version: Types.GetVersionResponse = await komodo.read('GetVersion', {});
console.log('🦎 Komodo version:', version.version, '🦎\n');
"""

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "server-76ich"

##

[[resource_sync]]
name = "sync"
[resource_sync.config]
repo = "d3adc3iii/dIIIhl"
git_account = "d3adc3iii"
resource_path = ["komodo/resources/main.toml"]
managed = true
include_variables = true

##

[[variable]]
name = "IMMICH_DB_PASSWORD"
value = "5069813x0o6wcbk0x5g2c8wr623gtiom"
is_secret = true