[[server]]
name = "komodo2"
[server.config]
address = "https://192.168.2.25:8120"
enabled = true

##

[[server]]
name = "server-76ich"
[server.config]
address = "https://periphery:8120"
enabled = true

##

[[stack]]
name = "gatus"
tags = ["gatus"]
[stack.config]
server = "komodo2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
reclone = true
run_directory = "server12/gatus"
environment = """
POSTGRES_DB=gatus
POSTGRES_USER=pgres_gat
POSTGRES_PASSWORD=[[GATUS_POSTGRES_PASSWORD]]
POSTGRES_DATA=/mnt/zApps/gatus/
"""

##

[[stack]]
name = "immich"
tags = ["immich"]
[stack.config]
server = "server-76ich"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
reclone = true
run_directory = "server13/immich-app"
environment = """
UPLOAD_LOCATION=/mnt/zApps/immich-komo
DB_DATA_LOCATION=./postgres
TZ=Asia/Singapore
IMMICH_VERSION=release
DB_PASSWORD=[[IMMICH_DB_PASSWORD]]
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
"""

##

[[stack]]
name = "karakeep"
tags = ["karakeep"]
[stack.config]
server = "server-76ich"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"
reclone = true
run_directory = "server13/karakeep-app"
environment = """
KARAKEEP_VERSION=release
NEXTAUTH_SECRET=[[KARA_NEXTAUTH_SECRET]]
MEILI_MASTER_KEY=[[KARA_MEILI_MASTER_KEY]]
NEXTAUTH_URL=http://localhost:3000
OPENAI_API_KEY=[[OPENAI_API_KEY]]
DATA_DIR=/mnt/zApps/karakeep/data
"""

##

[[repo]]
name = "diiihl"
[repo.config]
server = "server-76ich"
builder = "local"
git_account = "d3adc3iii"
repo = "d3adc3iii/dIIIhl"

##

[[procedure]]
name = "l"

##

[[action]]
name = "action"
[action.config]
file_contents = """
// Run actions using the pre initialized 'komodo' client.
const version: Types.GetVersionResponse = await komodo.read('GetVersion', {});
console.log('🦎 Komodo version:', version.version, '🦎\n');
"""

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "server-76ich"

##

[[resource_sync]]
name = "sync"
[resource_sync.config]
repo = "d3adc3iii/dIIIhl"
git_account = "d3adc3iii"
resource_path = ["komodo/resources/main.toml"]
managed = true
include_variables = true

##

[[variable]]
name = "IMMICH_DB_PASSWORD"
value = "5069813x0o6wcbk0x5g2c8wr623gtiom"
is_secret = true

##

[[variable]]
name = "OPENAI_API_KEY"
value = "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"
is_secret = true

##

[[variable]]
name = "KARA_MEILI_MASTER_KEY"
value = "MwldJwDmieQWtyMZTTVi2yb2T0r2ZHeCNrAdgKeG1vTwpLWy"
is_secret = true

##

[[variable]]
name = "KARA_NEXTAUTH_SECRET"
value = "4obmXxlcc8M7RIi95R4gGcqvH2mD29LLLx4C+sXAd7rLvNpM"
is_secret = true

##

[[variable]]
name = "GATUS_POSTGRES_PASSWORD"
value = "Kv+xW+QrDrzVHUnhPeGSEdBSlbSeNjSz+Kvx5kk1OvH07Rzz"
is_secret = true