[[resource_sync]]
name = "sync"
[resource_sync.config]
repo = "d3hl/dIIIhl"
git_account = "d3hl/dIIIhl"
webhook_secret = "ZDuIhK3CjhALwwkaZR8jiclMG8Z3xGbS"
resource_path = [
  "komodo/resources/resources.toml"
]
managed = true