---
  
- hosts: all
  vars:
    ansible_host_key_checking: false
  become: true
  become_user: d3

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes